---
name: Deploy Elasticsearch via ECK Operator
description: |
    Deploys Elasticsearch using the Elastic Cloud on Kubernetes (ECK) operator.
    Installs the ECK operator if not already present (idempotent).
    Uses scripts and manifests from generic/kubernetes/operator-based/elasticsearch/.

inputs:
    namespace:
        description: Kubernetes namespace for the Elasticsearch cluster
        required: false
        default: camunda
    elasticsearch-cluster-name:
        description: |
            Name of the Elasticsearch cluster (must match the metadata.name
            of the Elasticsearch resource in the manifest). Used to derive
            the service and secret names.
        required: false
        default: elasticsearch
    elasticsearch-cluster-file:
        description: |
            Path to the Elasticsearch cluster manifest.
            Relative to generic/kubernetes/operator-based/elasticsearch/.
        required: false
        default: elasticsearch-cluster.yml

outputs:
    elasticsearch-service:
        description: Elasticsearch service name
        value: ${{ format('{0}-es-http', inputs.elasticsearch-cluster-name) }}
    elasticsearch-port:
        description: Elasticsearch service port
        value: '9200'
    elasticsearch-secret:
        description: Name of the Elasticsearch elastic user secret
        value: ${{ format('{0}-es-elastic-user', inputs.elasticsearch-cluster-name) }}

runs:
    using: composite
    steps:
        - name: 🔍 Deploy ECK operator and Elasticsearch cluster
          shell: bash
          env:
              CAMUNDA_NAMESPACE: ${{ inputs.namespace }}
              ELASTICSEARCH_CLUSTER_FILE: ${{ inputs.elasticsearch-cluster-file }}
          run: |
              set -euo pipefail

              cd generic/kubernetes/operator-based/elasticsearch

              ./deploy.sh

              echo "✓ Elasticsearch cluster deployed in namespace ${{ inputs.namespace }}"
