---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
    name: keycloak
spec:
    instances: 1
    db:
        host: pg-keycloak-rw # this service is provided by the CNPG keycloak
        port: 5432
        database: keycloak
        schema: public
        usernameSecret:
            name: pg-keycloak-secret
            key: username
        passwordSecret:
            name: pg-keycloak-secret
            key: password
    http:
        httpEnabled: true
    transaction:
        xaEnabled: false
    additionalOptions:
        - name: hostname-path
          value: /auth
        - name: http-relative-path
          value: /auth
    hostname:
        hostname: ${CAMUNDA_DOMAIN}
        #  tlsSecret: example-tls
        #  backchannelDynamic: true
        strict: true
    resources:
        limits:
            cpu: 500m
            memory: 1Gi
        requests:
            cpu: 250m
            memory: 512Mi
    unsupported:
        podTemplate:
            spec:
                containers:
                    - env:
                          - name: KEYCLOAK_IMPORT
                            value: /opt/keycloak/data/import/realm-camunda-platform.json
                      envFrom:
                          - secretRef:
                                name: keycloak-realm-secrets
                      volumeMounts:
                          - name: realm-config-volume
                            mountPath: /opt/keycloak/data/import/realm-camunda-platform.json
                            subPath: realm-camunda-platform.json
                            readOnly: true
                      imagePullPolicy: IfNotPresent
                volumes:
                    - name: realm-config-volume
                      configMap:
                          name: keycloak-realm-config
