---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
    name: keycloak
spec:
    instances: 1
    db:
        host: pg-keycloak-rw # this service is provided by the CNPG keycloak
        port: 5432
        database: keycloak
        schema: public
        usernameSecret:
            name: pg-keycloak-secret
            key: username
        passwordSecret:
            name: pg-keycloak-secret
            key: password
    http:
        httpEnabled: true
    transaction:
        xaEnabled: false
    additionalOptions:
        - name: http-relative-path
          value: /auth
    ingress:
        enabled: true
        className: nginx
        annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /$1
            nginx.ingress.kubernetes.io/use-regex: 'true'
            nginx.ingress.kubernetes.io/ssl-redirect: 'false'
        rules:
            - host: ${CAMUNDA_DOMAIN}
              paths:
                  - path: /auth/(.*)
                    pathType: Prefix
    hostname:
        hostname: ${CAMUNDA_DOMAIN}
        strict: true
    resources:
        limits:
            cpu: 500m
            memory: 1Gi
        requests:
            cpu: 250m
            memory: 512Mi
