---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
    name: keycloak
spec:
    instances: 1
    db:
        host: pg-keycloak-rw # this service is provided by the CNPG keycloak
        port: 5432
        database: keycloak
        schema: public
        usernameSecret:
            name: pg-keycloak-secret
            key: username
        passwordSecret:
            name: pg-keycloak-secret
            key: password
    http:
        httpEnabled: true
    transaction:
        xaEnabled: false
    additionalOptions:
        - name: http-enabled
          value: 'true'
    hostname:
        hostname: localhost
        #  hostname: keycloak.example.com
        #  tlsSecret: example-tls
        #  backchannelDynamic: true
        strict: false
    resources:
        limits:
            cpu: 500m
            memory: 1Gi
        requests:
            cpu: 250m
            memory: 512Mi
