---
identityKeycloak:
    postgresql:
        enabled: true # use the embbeded database
    auth:
        existingSecret: identity-secret-for-components

global:
    compatibility:
        openshift:
            adaptSecurityContext: force # enforce compatibility with SCCs

    elasticsearch:
        enabled: true # use the embbeded elasticsearch

    identity:

        auth:
            publicIssuerUrl: http://localhost:18080/auth/realms/camunda-platform  # replace this with a port of your choice when you will do port forwarding

            zeebe:
                existingSecret:
                    name: identity-secret-for-components
            connectors:
                existingSecret:
                    name: identity-secret-for-components
            operate:
                redirectUrl: http://localhost:8081  # replace this with a port of your choice when you will do port forwarding
                existingSecret:
                    name: identity-secret-for-components
            tasklist:
                redirectUrl: http://localhost:8082  # replace this with a port of your choice when you will do port forwarding
                existingSecret:
                    name: identity-secret-for-components
            optimize:
                redirectUrl: http://localhost:8083  # replace this with a port of your choice when you will do port forwarding
                existingSecret:
                    name: identity-secret-for-components
            webModeler:
                redirectUrl: http://localhost:8084
            console:
                redirectUrl: http://localhost:8085
                existingSecret:
                    name: identity-secret-for-components

identity:
    fullURL: http://localhost:8080 # replace this with a port of your choice when you will do port forwarding

webModeler:
    enabled: false # by default, webModeler is not enabled

    restapi:
        mail:
            existingSecret: identity-secret-for-components # reference the smtp password
            fromAddress: changeme@example.com   # change this required value

console:
    enabled: false # by default, console is not enabled
