---
# This action cleans up Keycloak deployed via the Keycloak Operator with CNPG PostgreSQL.
# It removes the Keycloak CRD, pg-keycloak cluster, operators, and related secrets.
# Other CNPG clusters (pg-identity, pg-webmodeler) should be cleaned up separately
# using the kubernetes-cnpg-cluster-cleanup action.
name: Cleanup Keycloak Operator Deployment
description: Remove Keycloak deployed via Keycloak Operator and its CNPG PostgreSQL cluster (pg-keycloak)

inputs:
    namespace:
        description: Kubernetes namespace where Keycloak was deployed
        required: true
    skip-operator-uninstall:
        description: Skip uninstalling the operators (useful if shared across namespaces)
        required: false
        default: 'false'

runs:
    using: composite
    steps:
        - name: ðŸ—‘ï¸ Delete Keycloak CR
          shell: bash
          run: |
              set -euo pipefail
              echo "Deleting Keycloak CR..."
              if kubectl get keycloak keycloak -n "${{ inputs.namespace }}" &>/dev/null; then
                kubectl delete keycloak keycloak -n "${{ inputs.namespace }}" --timeout=120s || true
              else
                echo "Keycloak CR not found, skipping..."
              fi

        - name: ðŸ—‘ï¸ Delete PostgreSQL Cluster (pg-keycloak)
          uses: ./.github/actions/kubernetes-cnpg-cluster-cleanup
          with:
              namespace: ${{ inputs.namespace }}
              cluster-name: pg-keycloak
              skip-operator-uninstall: 'true'

        - name: ðŸ—‘ï¸ Delete Keycloak identity secrets
          shell: bash
          run: |
              set -euo pipefail
              echo "Deleting Keycloak identity secrets..."
              if kubectl get secret identity-secret-for-components -n "${{ inputs.namespace }}" &>/dev/null; then
                kubectl delete secret identity-secret-for-components -n "${{ inputs.namespace }}" || true
                echo "Deleted secret: identity-secret-for-components"
              else
                echo "Secret identity-secret-for-components not found, skipping..."
              fi

        - name: ðŸ—‘ï¸ Uninstall Keycloak Operator and CRDs
          if: inputs.skip-operator-uninstall != 'true'
          shell: bash
          run: |
              set -euo pipefail
              echo "Uninstalling Keycloak Operator..."

              # Delete the operator deployment
              if kubectl get namespace keycloak-system &>/dev/null; then
                kubectl delete namespace keycloak-system --timeout=60s || true
              else
                echo "Namespace keycloak-system not found, skipping..."
              fi

              # Delete Keycloak CRDs
              echo "Deleting Keycloak CRDs..."
              for crd in keycloaks.k8s.keycloak.org keycloakrealmimports.k8s.keycloak.org; do
                if kubectl get crd "$crd" &>/dev/null; then
                  kubectl delete crd "$crd" --timeout=60s || true
                  echo "Deleted CRD: $crd"
                else
                  echo "CRD $crd not found, skipping..."
                fi
              done

        - name: ðŸ—‘ï¸ Uninstall CloudNativePG Operator
          if: inputs.skip-operator-uninstall != 'true'
          shell: bash
          run: |
              set -euo pipefail
              echo "Uninstalling CloudNativePG Operator..."

              CNPG_NS="cnpg-system"

              # Delete the operator deployment (installed via raw manifests)
              if kubectl get deployment cnpg-controller-manager -n "$CNPG_NS" &>/dev/null; then
                kubectl delete deployment cnpg-controller-manager -n "$CNPG_NS" --timeout=60s || true
                echo "Deleted CNPG controller manager deployment"
              else
                echo "CNPG controller manager not found, skipping..."
              fi

              # Delete CNPG CRDs
              echo "Deleting CNPG CRDs..."
              for crd in $(kubectl get crd -o name 2>/dev/null | grep -E '\.postgresql\.cnpg\.io$' || true); do
                kubectl delete "$crd" --timeout=60s || true
                echo "Deleted CRD: $crd"
              done

              # Delete operator namespace if empty
              if kubectl get namespace "$CNPG_NS" &>/dev/null; then
                if [ "$(kubectl get all -n "$CNPG_NS" -o name 2>/dev/null | wc -l)" -eq 0 ]; then
                  kubectl delete namespace "$CNPG_NS" --timeout=60s || true
                else
                  echo "Namespace $CNPG_NS still has resources, not deleting"
                fi
              fi

        - name: âœ… Cleanup completed
          shell: bash
          run: |
              echo "Keycloak Operator cleanup completed successfully"
