---
# This action cleans up Keycloak deployed via the Keycloak Operator with CNPG PostgreSQL.
# It removes the Keycloak CRD, pg-keycloak cluster, Keycloak operator, and related secrets.
# CNPG operator cleanup should be handled separately using kubernetes-cnpg-cluster-cleanup.
name: Cleanup Keycloak Operator Deployment
description: Remove Keycloak deployed via Keycloak Operator and its CNPG PostgreSQL cluster (pg-keycloak)

inputs:
    namespace:
        description: Kubernetes namespace where Keycloak was deployed
        required: false
        default: camunda

runs:
    using: composite
    steps:
        - name: ðŸ—‘ï¸ Delete Keycloak CR
          shell: bash
          run: |
              set -euo pipefail
              echo "Deleting Keycloak CR..."
              if kubectl get keycloak keycloak -n "${{ inputs.namespace }}" &>/dev/null; then
                kubectl delete keycloak keycloak -n "${{ inputs.namespace }}" --timeout=120s || true
              else
                echo "Keycloak CR not found, skipping..."
              fi

        - name: ðŸ—‘ï¸ Delete PostgreSQL Cluster (pg-keycloak)
          uses: ./.github/actions/kubernetes-cnpg-cluster-cleanup
          with:
              namespace: ${{ inputs.namespace }}
              cluster-name: pg-keycloak
              skip-operator-uninstall: 'true'

        - name: ðŸ—‘ï¸ Delete Identity component secrets
          shell: bash
          run: |
              set -euo pipefail
              echo "Deleting Identity component secrets..."
              if kubectl get secret identity-secret-for-components -n "${{ inputs.namespace }}" &>/dev/null; then
                kubectl delete secret identity-secret-for-components -n "${{ inputs.namespace }}" || true
                echo "Deleted secret: identity-secret-for-components"
              else
                echo "Secret identity-secret-for-components not found, skipping..."
              fi

        - name: ðŸ—‘ï¸ Uninstall Keycloak Operator and CRDs
          shell: bash
          run: |
              set -euo pipefail
              echo "Uninstalling Keycloak Operator..."

              # Delete the operator deployment
              if kubectl get namespace keycloak-system &>/dev/null; then
                kubectl delete namespace keycloak-system --timeout=60s || true
              else
                echo "Namespace keycloak-system not found, skipping..."
              fi

              # Delete Keycloak CRDs
              echo "Deleting Keycloak CRDs..."
              for crd in keycloaks.k8s.keycloak.org keycloakrealmimports.k8s.keycloak.org; do
                if kubectl get crd "$crd" &>/dev/null; then
                  kubectl delete crd "$crd" --timeout=60s || true
                  echo "Deleted CRD: $crd"
                else
                  echo "CRD $crd not found, skipping..."
                fi
              done

        - name: âœ… Cleanup completed
          shell: bash
          run: |
              echo "Keycloak Operator cleanup completed successfully"
