---
name: Cleanup ECK Elasticsearch Deployment
description: |
    Removes the Elasticsearch cluster and optionally the ECK operator.

inputs:
    namespace:
        description: Kubernetes namespace where Elasticsearch was deployed
        required: true
    skip-operator-uninstall:
        description: Skip uninstalling the ECK operator
        required: false
        default: 'false'
    eck-operator-namespace:
        description: Namespace for the ECK operator
        required: false
        default: elastic-system

outputs: {}

runs:
    using: composite
    steps:
        - name: ðŸ—‘ï¸ Delete Elasticsearch cluster
          shell: bash
          run: |
              set -euo pipefail
              echo "Deleting Elasticsearch clusters in namespace ${{ inputs.namespace }}..."
              if kubectl get elasticsearch -n "${{ inputs.namespace }}" &>/dev/null; then
                kubectl delete elasticsearch --all -n "${{ inputs.namespace }}" --timeout=120s || true
                echo "Deleted Elasticsearch clusters"
              else
                echo "No Elasticsearch clusters found, skipping..."
              fi

        - name: ðŸ—‘ï¸ Delete Elasticsearch secrets
          shell: bash
          run: |
              set -euo pipefail
              echo "Deleting Elasticsearch secrets..."
              ES_SECRETS=(
                elasticsearch-es-elastic-user
                elasticsearch-es-http-certs-internal
                elasticsearch-es-http-certs-public
                elasticsearch-es-transport-certs-public
                elasticsearch-es-internal-users
                elasticsearch-es-remote-ca
                elasticsearch-es-xpack-file-realm
                elasticsearch-es-file-settings
              )
              for secret in "${ES_SECRETS[@]}"; do
                if kubectl get secret "$secret" -n "${{ inputs.namespace }}" &>/dev/null; then
                  kubectl delete secret "$secret" -n "${{ inputs.namespace }}" || true
                  echo "Deleted secret: $secret"
                else
                  echo "Secret $secret not found, skipping..."
                fi
              done

        - name: ðŸ—‘ï¸ Uninstall ECK Operator
          if: inputs.skip-operator-uninstall != 'true'
          shell: bash
          run: |
              set -euo pipefail
              echo "Uninstalling ECK Operator..."

              # Delete operator namespace (contains the operator statefulset)
              if kubectl get namespace "${{ inputs.eck-operator-namespace }}" &>/dev/null; then
                kubectl delete namespace "${{ inputs.eck-operator-namespace }}" --timeout=60s || true
                echo "Deleted namespace: ${{ inputs.eck-operator-namespace }}"
              else
                echo "Namespace ${{ inputs.eck-operator-namespace }} not found, skipping..."
              fi

              # Delete ECK CRDs
              echo "Deleting ECK CRDs..."
              for crd in $(kubectl get crd -o name 2>/dev/null | grep -E '\.k8s\.elastic\.co$' || true); do
                kubectl delete "$crd" --timeout=60s || true
                echo "Deleted CRD: $crd"
              done

        - name: âœ… ECK cleanup completed
          shell: bash
          run: |
              echo "ECK Elasticsearch cleanup completed"
