#!/bin/bash
set -euo pipefail

# Create camunda-credentials with randomly generated credentials
# This replaces the removed global.secrets.autoGenerated Helm chart feature.
#
# Must run AFTER operators-deploy.sh and BEFORE camunda-deploy-*.sh
#
# Key names match: generic/kubernetes/operator-based/tests/utils/camunda-values-identity-secrets.yml

NAMESPACE="${CAMUNDA_NAMESPACE:-camunda}"

echo "🔐 Creating camunda-credentials in namespace '$NAMESPACE'..."

# Generate random secrets for all components
CONNECTORS_SECRET="$(openssl rand -hex 16)"
CONSOLE_SECRET="$(openssl rand -hex 16)"
WEB_MODELER_SECRET="$(openssl rand -hex 16)"
ORCHESTRATION_SECRET="$(openssl rand -hex 16)"
OPTIMIZE_SECRET="$(openssl rand -hex 16)"
ADMIN_PASSWORD="$(openssl rand -hex 16)"
FIRST_USER_PASSWORD="$(openssl rand -hex 16)"

kubectl create secret generic camunda-credentials \
    --namespace "$NAMESPACE" \
    --from-literal=identity-connectors-client-token="$CONNECTORS_SECRET" \
    --from-literal=identity-console-client-token="$CONSOLE_SECRET" \
    --from-literal=identity-webmodeler-client-token="$WEB_MODELER_SECRET" \
    --from-literal=identity-orchestration-client-token="$ORCHESTRATION_SECRET" \
    --from-literal=identity-optimize-client-token="$OPTIMIZE_SECRET" \
    --from-literal=identity-admin-client-token="$ADMIN_PASSWORD" \
    --from-literal=identity-first-user-password="$FIRST_USER_PASSWORD" \
    --dry-run=client -o yaml | kubectl apply -f -

echo "✅ camunda-credentials created"
echo ""
echo "To verify:"
echo "  kubectl get secret camunda-credentials -n $NAMESPACE -o yaml"
