---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: premium-lrs-sc
    annotations:
        storageclass.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/azure-disk
parameters:
    storageaccounttype: PremiumV2_LRS
    kind: Managed
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
