---
name: Configure AWS CLI
description: Import AWS Secrets from Vault and configure AWS CLI profile
# The official action do not support profiles

inputs:
    vault-addr:
        description: The URL of the Vault server
        required: true
    vault-role-id:
        description: The Vault Role ID
        required: true
    vault-secret-id:
        description: The Vault Secret ID
        required: true
    aws-profile:
        description: AWS CLI profile name
        required: true
    aws-region:
        description: AWS region
        required: true

runs:
    using: composite
    steps:
        - name: Import Secrets from Vault
          id: secrets
          uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc # v4
          with:
              url: ${{ inputs.vault-addr }}
              method: approle
              roleId: ${{ inputs.vault-role-id }}
              secretId: ${{ inputs.vault-secret-id }}
              exportEnv: false
              secrets: |
                  secret/data/products/infrastructure-experience/ci/common AWS_ACCESS_KEY;
                  secret/data/products/infrastructure-experience/ci/common AWS_SECRET_KEY;

        - name: Add AWS CLI credentials to profile
          shell: bash
          run: |
              set -euo pipefail
              aws configure set aws_access_key_id "${AWS_ACCESS_KEY}" --profile "${INPUTS_AWS_PROFILE}"
              aws configure set aws_secret_access_key "${AWS_SECRET_KEY}" --profile "${INPUTS_AWS_PROFILE}"
              aws configure set region "${INPUTS_AWS_REGION}" --profile "${INPUTS_AWS_PROFILE}"
          env:
              AWS_ACCESS_KEY: ${{ steps.secrets.outputs.AWS_ACCESS_KEY }}
              AWS_SECRET_KEY: ${{ steps.secrets.outputs.AWS_SECRET_KEY }}
              INPUTS_AWS_PROFILE: ${{ inputs.aws-profile }}
              INPUTS_AWS_REGION: ${{ inputs.aws-region }}
