---
matrix:
    distro:
        - name: OpenShift 4.19
          schedule_only: false
          # renovate: datasource=custom.rosa-camunda depName=red-hat-openshift versioning=regex:^4(\.(?<minor>\d+))?(\.(?<patch>\d+))?$
          version: 4.19.7
          clusterName: op-based # cluster name for operator-based tests
          type: openshift
          # - name: EKS Latest
          #   schedule_only: false
          #   # renovate: datasource=github-releases depName=kubernetes/kubernetes versioning=kubernetes
          #   clusterName: op-based-eks # cluster name for operator-based EKS tests
          #   type: eks

    scenario:
        - name: operator-based
          shortName: opb

    # TODO: revert
    # - name: no-domain
    #   desc: Setup operator-basedc stack without domain configuration.
    declination:
        - name: domain
          desc: Setup operator-based stack with domain configuration.
