---
matrix:
    distro:
        - name: EKS
          schedule_only: false

    scenario:
        - name: eks-single-region
          # ! Unlike ROSA, 'private_vpc' is defined in 'scenario' and not in 'distro'.
          private_vpc: false
          oidc_enabled: false  # No OIDC for basic scenario

        - name: eks-single-region-irsa
          private_vpc: true
          oidc_enabled: false  # No OIDC for IRSA scenario
    declination:
        - name: no-domain
          desc: Setup chart in production-like setup with Ingress and TLS.
        - name: domain
          desc: Setup chart in production-like setup without Ingress and TLS.
        - name: oidc
          desc: Setup chart with external OIDC provider (EntraID for tests) instead of Keycloak.
