---
matrix:
    distro:
        - name: EKS
          schedule_only: false

    scenario:
        - name: eks-single-region
          # ! Unlike ROSA, 'private_vpc' is defined in 'scenario' and not in 'distro'.
          private_vpc: false
          # Auth provider: 'keycloak' (embedded) or 'oidc' (external like Cognito, EntraID)
          # TODO: Re-enable 'oidc' (AWS Cognito) once https://github.com/camunda/camunda/issues/44650 is fixed
          #       Currently, Cognito M2M tokens lack 'aud' claim and Camunda's AudienceValidator rejects them.
          #       The workaround (CAMUNDA_SECURITY_AUTHENTICATION_OIDC_AUDIENCES="") also fails due to a bug
          #       in TokenValidatorFactory that doesn't handle empty audience lists.
          auth_provider: keycloak

        - name: eks-single-region-irsa
          private_vpc: true
          auth_provider: keycloak

    declination:
        - name: no-domain
          desc: Setup chart without Ingress and TLS (access via port-forward).
        - name: domain
          desc: Setup chart in production-like setup with Ingress and TLS.
