---
matrix:
    distro:
        - name: EKS
          schedule_only: false

    scenario:
        - name: eks-single-region
          # ! Unlike ROSA, 'private_vpc' is defined in 'scenario' and not in 'distro'.
          private_vpc: false

        - name: eks-single-region-irsa
          private_vpc: true
    declination:
        - name: no-domain
          desc: Setup chart in production-like setup with Ingress and TLS.
          # TODO: revert
          # - name: domain
          #   desc: Setup chart in production-like setup without Ingress and TLS.
