---
matrix:
    distro:
        - name: EKS
          schedule_only: false

    scenario:
        - name: eks-single-region
          # ! Unlike ROSA, 'private_vpc' is defined in 'scenario' and not in 'distro'.
          private_vpc: false
          # Auth provider: 'keycloak' (embedded) or 'oidc' (external like Cognito, EntraID)
          auth_provider: oidc

        - name: eks-single-region-irsa
          private_vpc: true
          auth_provider: keycloak

    declination:
        - name: no-domain
          desc: Setup chart without Ingress and TLS (access via port-forward).
        - name: domain
          desc: Setup chart in production-like setup with Ingress and TLS.
