---
matrix:
    distro:
        - name: EKS
          schedule_only: false

    scenario:
        - name: eks-single-region
        - name: eks-single-region-irsa

    declination:
        # TODO: test no-domain later
        # - name: domain
        #   desc: Setup chart in production-like setup without Ingress and TLS.
        - name: no-domain
          desc: Setup chart in production-like setup with Ingress and TLS.
