---
matrix:
    distro:
        - name: EKS
          schedule_only: false
          private_vpc: true

    scenario:
        - name: eks-single-region
        - name: eks-single-region-irsa

    declination:
        - name: no-domain
          desc: Setup chart in production-like setup with Ingress and TLS.
        - name: domain
          desc: Setup chart in production-like setup without Ingress and TLS.
