---
matrix:
    distro:
        - name: AKS
          schedule_only: false

    scenario:
        - name: aks-single-region
          # Auth provider options:
          #   - 'keycloak-operator': Keycloak deployed via Keycloak Operator with CNPG PostgreSQL
          #   - 'oidc': External OIDC provider (EntraID, Cognito)
          # TODO: Add 'oidc' support with Azure EntraID
          auth_provider: keycloak-operator

    declination:
        - name: no-domain
          desc: Setup chart in production-like setup without Ingress and TLS.
        - name: domain
          desc: Setup chart in production-like setup with Ingress and TLS.
