---
matrix:
    declination:
        - name: no-domain
          desc: Setup chart in production-like setup without Ingress and TLS.
        - name: domain
          desc: Setup chart in production-like setup with Ingress and TLS.
