---
matrix:
    distro:
        - name: AKS
          schedule_only: false

    scenario:
        - name: aks-single-region

    declination:
        # TODO : revert, testing domain only for the moment
        # - name: no-domain
        #   desc: Setup chart in production-like setup without Ingress and TLS.
        - name: domain
          desc: Setup chart in production-like setup with Ingress and TLS.
