---
matrix:
    distro:
        - name: AKS
          schedule_only: false

    scenario:
        - name: aks-single-region

    declination:
        - name: no-domain
          desc: Setup chart in production-like setup without Ingress and TLS.
          # TODO: revert
          # - name: domain
          #   desc: Setup chart in production-like setup with Ingress and TLS.
