---
name: Deploy Keycloak via Operator
description: |
    Deploys Keycloak using the Keycloak Operator with CloudNativePG PostgreSQL.
    Uses scripts from generic/kubernetes/operator-based/ for deployment.

inputs:
    namespace:
        description: Kubernetes namespace for deployment
        required: false
        default: camunda
    keycloak-mode:
        description: |
            Keycloak deployment mode:
            - 'domain': With ingress for domain access (nginx)
            - 'domain-openshift': With ingress for OpenShift router
            - 'no-domain': Without ingress (port-forward access)
        required: false
        default: no-domain
    domain-name:
        description: Domain name (required for domain mode)
        required: false
        default: ''
    cnpg-operator-namespace:
        description: Namespace for CNPG operator
        required: false
        default: cnpg-system

outputs:
    keycloak-admin-secret:
        description: Name of the Keycloak admin secret
        value: keycloak-initial-admin
    keycloak-service:
        description: Keycloak service name
        value: keycloak-service
    keycloak-port:
        description: Keycloak service port
        value: '8080'

runs:
    using: composite
    steps:
        - name: Install CloudNativePG Operator
          shell: bash
          env:
              # renovate: datasource=github-releases depName=cloudnative-pg/cloudnative-pg
              CNPG_VERSION: 1.28.0
          run: |
              set -euo pipefail

              echo "🐘 Installing CloudNativePG operator v${CNPG_VERSION}..."

              kubectl apply -n "${{ inputs.cnpg-operator-namespace }}" --server-side -f \
                  "https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-${CNPG_VERSION%.*}/releases/cnpg-${CNPG_VERSION}.yaml"

              kubectl rollout status deployment \
                  -n "${{ inputs.cnpg-operator-namespace }}" cnpg-controller-manager \
                  --timeout=300s

              echo "✓ CloudNativePG operator deployed"

        - name: Create PostgreSQL secrets for Keycloak
          shell: bash
          env:
              CAMUNDA_NAMESPACE: ${{ inputs.namespace }}
          run: |
              set -euo pipefail

              echo "🔐 Creating PostgreSQL secrets for Keycloak..."

              # Function to create or get secret (same as in generic script)
              create_or_get_secret() {
                  local secret_name=$1
                  local username=$2

                  if kubectl get secret "$secret_name" -n "$CAMUNDA_NAMESPACE" >/dev/null 2>&1; then
                      echo "✓ Secret $secret_name already exists"
                  else
                      echo "Creating new secret $secret_name"
                      kubectl create secret generic "$secret_name" -n "$CAMUNDA_NAMESPACE" \
                          --from-literal=username="$username" \
                          --from-literal=password="$(openssl rand -base64 18)"
                  fi
              }

              # Keycloak superuser and bootstrap secrets
              create_or_get_secret "pg-keycloak-superuser-secret" "root"
              create_or_get_secret "pg-keycloak-secret" "keycloak"

              echo "✓ PostgreSQL secrets created"

        - name: Deploy PostgreSQL cluster for Keycloak
          shell: bash
          run: |
              set -euo pipefail

              NAMESPACE="${{ inputs.namespace }}"

              echo "🐘 Deploying PostgreSQL cluster for Keycloak..."

              # Extract only pg-keycloak cluster from the multi-cluster manifest
              yq 'select(.metadata.name == "pg-keycloak")' \
                  "generic/kubernetes/operator-based/postgresql/postgresql-clusters.yml" | \
                  kubectl apply -n "$NAMESPACE" --server-side -f -

              echo "⏳ Waiting for PostgreSQL cluster to be ready..."
              kubectl wait --for=condition=Ready --timeout=600s cluster pg-keycloak -n "$NAMESPACE"
              echo "✓ PostgreSQL cluster deployed"

        - name: Install Keycloak Operator and deploy instance
          shell: bash
          env:
              CAMUNDA_NAMESPACE: ${{ inputs.namespace }}
              CAMUNDA_DOMAIN: ${{ inputs.domain-name }}
          run: |
              set -euo pipefail

              MODE="${{ inputs.keycloak-mode }}"
              KEYCLOAK_DIR="generic/kubernetes/operator-based/keycloak"

              # Select the right config file based on mode
              case "$MODE" in
                  "no-domain")
                      export KEYCLOAK_CONFIG_FILE="${KEYCLOAK_DIR}/keycloak-instance-no-domain.yml"
                      ;;
                  "domain")
                      export KEYCLOAK_CONFIG_FILE="${KEYCLOAK_DIR}/keycloak-instance-domain-nginx.yml"
                      ;;
                  "domain-openshift")
                      export KEYCLOAK_CONFIG_FILE="${KEYCLOAK_DIR}/keycloak-instance-domain-openshift.yml"
                      ;;
                  *)
                      echo "Error: Unknown mode '$MODE'" >&2
                      exit 1
                      ;;
              esac

              echo "🔑 Deploying Keycloak (mode: $MODE, config: $KEYCLOAK_CONFIG_FILE)..."

              # Run the deploy script
              "${KEYCLOAK_DIR}/deploy.sh"

              echo "✓ Keycloak deployed"
              kubectl wait --for=condition=Ready --timeout=600s keycloak --all -n "$NAMESPACE"
              echo "✓ Keycloak instance deployed"

        - name: Verify Keycloak admin secret
          shell: bash
          run: |
              set -euo pipefail

              NAMESPACE="${{ inputs.namespace }}"

              if kubectl get secret keycloak-initial-admin -n "$NAMESPACE" >/dev/null 2>&1; then
                  echo "✓ keycloak-initial-admin secret exists"
              else
                  echo "❌ ERROR: keycloak-initial-admin secret not found!"
                  exit 1
              fi

        - name: Create identity secrets for components
          shell: bash
          run: |
              set -euo pipefail

              NAMESPACE="${{ inputs.namespace }}"

              echo "🔐 Creating identity-secret-for-components..."

              # Generate random secrets for all components
              IDENTITY_CLIENT_SECRET="$(openssl rand -hex 16)"
              OPTIMIZE_CLIENT_SECRET="$(openssl rand -hex 16)"
              ORCHESTRATION_CLIENT_SECRET="$(openssl rand -hex 16)"
              CONNECTORS_CLIENT_SECRET="$(openssl rand -hex 16)"
              CONSOLE_CLIENT_SECRET="$(openssl rand -hex 16)"
              WEBMODELER_CLIENT_SECRET="$(openssl rand -hex 16)"
              FIRST_USER_PASSWORD="$(openssl rand -hex 16)"

              kubectl create secret generic identity-secret-for-components \
                  --namespace "$NAMESPACE" \
                  --from-literal=identity-client-secret="$IDENTITY_CLIENT_SECRET" \
                  --from-literal=optimize-client-secret="$OPTIMIZE_CLIENT_SECRET" \
                  --from-literal=orchestration-client-secret="$ORCHESTRATION_CLIENT_SECRET" \
                  --from-literal=connectors-client-secret="$CONNECTORS_CLIENT_SECRET" \
                  --from-literal=console-client-secret="$CONSOLE_CLIENT_SECRET" \
                  --from-literal=webmodeler-client-secret="$WEBMODELER_CLIENT_SECRET" \
                  --from-literal=identity-first-user-password="$FIRST_USER_PASSWORD" \
                  --dry-run=client -o yaml | kubectl apply -f -

              echo "✓ identity-secret-for-components created"
