---
matrix:
    distro:
        # /!\ BEFORE ADDING/REMOVING A VERSION:
        # /!\ Please keep this matrix synced with the official documentation:
        # https://github.com/camunda/camunda-docs/blob/main/docs/self-managed/setup/deploy/openshift/redhat-openshift.md?plain=1#L2
        # According to https://access.redhat.com/support/policy/updates/openshift, this matrix should reference the first and the last of the supported versions of OpenShift
        - name: OpenShift latest
          schedule_only: false
          # ! Unlike EKS, 'private_vpc' is defined in 'distro' and not in 'scenario'.
          private_vpc: true # latest always use vpn, olders use public
          # renovate: datasource=custom.rosa-camunda depName=red-hat-openshift versioning=regex:^4(\.(?<minor>\d+))?(\.(?<patch>\d+))?$
          version: 4.20.3
          # /!\ Warning: When a new minor version of OpenShift is released,
          # you must update the N-3 versions in this matrix.
          # rationale: Red Hat supports the last four minor versions of OpenShift.
          # Therefore, to ensure compatibility and support, we test the latest and the older.
          # For more details, refer to the official support policy at https://endoflife.date/red-hat-openshift.

        - name: OpenShift 4.17
          schedule_only: true
          private_vpc: false
          # TODO: EOL this version on 2026-04-01
          # renovate: datasource=custom.rosa-camunda depName=red-hat-openshift versioning=regex:^4.17(\.(?<patch>\d+))?$
          version: 4.17.44

    scenario:
        - name: rosa-hcp-single-region
          # Auth provider options:
          #   - 'keycloak-operator': Keycloak deployed via Keycloak Operator with CNPG PostgreSQL
          #   - 'oidc': External OIDC provider (Cognito, EntraID)
          # TODO: Add 'oidc' support with AWS Cognito
          auth_provider: keycloak-operator

    declination:
        - name: no-domain
          desc: Setup chart in production-like setup with Ingress and TLS.
        - name: domain
          desc: Setup chart in production-like setup without Ingress and TLS.
