#!/usr/bin/env python3
"""Upsert a section in the shared Helm-deprecation PR comment.

The action posts a single comment per PR (identified by a hidden HTML marker)
with one section per (workflow, job, release-name, namespace, section-key)
tuple. Each invocation either replaces its own section, appends a new one,
removes its section if it has no findings, or deletes the comment entirely
when the last section disappears.

Designed to converge under racing matrix jobs by re-fetching the comment
on every retry. Failure to post is logged as a workflow warning but never
fails the action -- the PR comment is advisory.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import random
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

MARKER = "<!-- helm-deprecation-check -->"
HEADER = (
    f"{MARKER}\n"
    "# 🚧 Helm chart issues detected\n\n"
    "This comment is auto-generated by the "
    "[`internal-helm-deprecation-check`](https://github.com/camunda/"
    "camunda-deployment-references/tree/main/.github/actions/"
    "internal-helm-deprecation-check) action and refreshes on every "
    "workflow run.\n\n"
    "See the [Camunda Helm upgrade docs]"
    "(https://docs.camunda.io/docs/self-managed/deployment/helm/upgrade/) "
    "for migration guidance.\n"
)
SECTION_START_FMT = "<!-- section:{sid}:start -->"
SECTION_END_FMT = "<!-- section:{sid}:end -->"
ANY_SECTION_RE = re.compile(r"<!-- section:[0-9a-f]{12}:start -->")

MAX_ATTEMPTS = 5


def section_id(*parts: str) -> str:
    raw = "|".join(parts)
    return hashlib.sha1(raw.encode("utf-8")).hexdigest()[:12]


API_BASE = os.environ.get("GITHUB_API_URL", "https://api.github.com")


def _token() -> str:
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token:
        raise RuntimeError("GH_TOKEN/GITHUB_TOKEN not set")
    return token


def gh_api(
    path: str,
    *,
    method: str = "GET",
    body: dict | None = None,
    query: dict | None = None,
) -> tuple[int, bytes]:
    """Call the GitHub REST API. Returns (status_code, raw_body)."""
    url = f"{API_BASE}{path}"
    if query:
        url = f"{url}?{urllib.parse.urlencode(query)}"
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)  # noqa: S310 -- https only
    req.add_header("Authorization", f"Bearer {_token()}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("User-Agent", "internal-helm-deprecation-check")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req) as resp:  # noqa: S310 -- https only
            return resp.status, resp.read()
    except urllib.error.HTTPError as exc:
        payload = exc.read() or b""
        raise RuntimeError(
            f"GitHub API {method} {path} failed ({exc.code}): "
            f"{payload.decode('utf-8', errors='replace')}"
        ) from exc


def find_existing_comment(repo: str, pr_number: int) -> dict | None:
    """Return the first issue comment containing the marker, or None."""
    page = 1
    while True:
        _, raw = gh_api(
            f"/repos/{repo}/issues/{pr_number}/comments",
            query={"per_page": 100, "page": page},
        )
        comments = json.loads(raw)
        if not comments:
            return None
        for c in comments:
            if MARKER in (c.get("body") or ""):
                return c
        if len(comments) < 100:
            return None
        page += 1


def splice_section(body: str, sid: str, section_block: str) -> str:
    """Replace the section identified by sid in body, or append if missing."""
    start = SECTION_START_FMT.format(sid=sid)
    end = SECTION_END_FMT.format(sid=sid)
    pattern = re.compile(
        rf"{re.escape(start)}.*?{re.escape(end)}\n*",
        re.DOTALL,
    )
    if pattern.search(body):
        return pattern.sub(section_block, body)
    if not body.endswith("\n"):
        body += "\n"
    return body + "\n" + section_block


def remove_section(body: str, sid: str) -> str:
    start = SECTION_START_FMT.format(sid=sid)
    end = SECTION_END_FMT.format(sid=sid)
    pattern = re.compile(
        rf"{re.escape(start)}.*?{re.escape(end)}\n*",
        re.DOTALL,
    )
    return pattern.sub("", body)


def build_section(
    sid: str,
    title: str,
    findings: str,
    run_url: str,
    timestamp: str,
) -> str:
    return (
        f"{SECTION_START_FMT.format(sid=sid)}\n"
        f"## {title}\n\n"
        f"_Updated by [run]({run_url}) at {timestamp}_\n\n"
        f"{findings.rstrip()}\n"
        f"{SECTION_END_FMT.format(sid=sid)}\n"
    )


def has_any_section(body: str) -> bool:
    return bool(ANY_SECTION_RE.search(body))


def post_comment(repo: str, pr_number: int, body: str) -> dict:
    _, raw = gh_api(
        f"/repos/{repo}/issues/{pr_number}/comments",
        method="POST",
        body={"body": body},
    )
    return json.loads(raw)


def patch_comment(repo: str, comment_id: int, body: str) -> dict:
    _, raw = gh_api(
        f"/repos/{repo}/issues/comments/{comment_id}",
        method="PATCH",
        body={"body": body},
    )
    return json.loads(raw)


def delete_comment(repo: str, comment_id: int) -> None:
    gh_api(
        f"/repos/{repo}/issues/comments/{comment_id}",
        method="DELETE",
    )


def attempt_upsert(
    *,
    repo: str,
    pr_number: int,
    sid: str,
    section_block: str | None,
) -> bool:
    """One read-modify-write attempt. Returns True on success."""
    existing = find_existing_comment(repo, pr_number)

    if existing is None:
        if section_block is None:
            # Nothing to post and no comment to update: clean state.
            return True
        new_body = HEADER + "\n" + section_block
        created = post_comment(repo, pr_number, new_body)
        # Verify our marker round-tripped.
        return MARKER in (created.get("body") or "") and sid in (created.get("body") or "")

    body = existing.get("body") or ""
    comment_id = existing["id"]

    if section_block is None:
        new_body = remove_section(body, sid)
    else:
        new_body = splice_section(body, sid, section_block)

    # Make sure the header is present.
    if MARKER not in new_body:
        new_body = HEADER + "\n" + new_body.lstrip()

    if not has_any_section(new_body):
        delete_comment(repo, comment_id)
        # Verify: re-fetch and confirm gone.
        again = find_existing_comment(repo, pr_number)
        return again is None or again["id"] != comment_id

    if new_body == body:
        return True

    updated = patch_comment(repo, comment_id, new_body)
    updated_body = updated.get("body") or ""
    if section_block is None:
        return sid not in updated_body
    return SECTION_START_FMT.format(sid=sid) in updated_body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pr-number", required=True, type=int)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--workflow", required=True)
    parser.add_argument("--job", required=True)
    parser.add_argument("--release-name", required=True)
    parser.add_argument("--namespace", required=True)
    parser.add_argument("--kube-context", default="")
    parser.add_argument("--section-key", default="")
    parser.add_argument("--run-url", required=True)
    parser.add_argument("--findings-file", required=True, type=Path)
    args = parser.parse_args()

    findings = ""
    if args.findings_file.is_file():
        findings = args.findings_file.read_text(encoding="utf-8").strip()

    sid = section_id(
        args.workflow,
        args.job,
        args.release_name,
        args.namespace,
        args.kube_context,
        args.section_key,
    )

    if findings:
        ctx_suffix = f" (context `{args.kube_context}`)" if args.kube_context else ""
        title = (
            f"`{args.workflow}` / `{args.job}` — release "
            f"`{args.release_name}` in `{args.namespace}`{ctx_suffix}"
        )
        timestamp = dt.datetime.now(tz=dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        section_block: str | None = build_section(
            sid=sid,
            title=title,
            findings=findings,
            run_url=args.run_url,
            timestamp=timestamp,
        )
    else:
        section_block = None

    last_error = ""
    for attempt in range(1, MAX_ATTEMPTS + 1):
        try:
            if attempt_upsert(
                repo=args.repo,
                pr_number=args.pr_number,
                sid=sid,
                section_block=section_block,
            ):
                action = "cleared" if section_block is None else "updated"
                print(f"PR #{args.pr_number} comment {action} (attempt {attempt}).")
                return 0
            last_error = "verification mismatch"
        except RuntimeError as exc:
            last_error = str(exc)
        if attempt < MAX_ATTEMPTS:
            sleep_s = 1 + random.random() * 3  # noqa: S311 -- jitter, not crypto
            print(
                f"Comment upsert attempt {attempt} did not converge "
                f"({last_error}); retrying in {sleep_s:.1f}s.",
                file=sys.stderr,
            )
            time.sleep(sleep_s)

    print(
        f"::warning::Failed to upsert Helm-deprecation PR comment after "
        f"{MAX_ATTEMPTS} attempts: {last_error}. The workflow will not be "
        f"failed; re-run to retry.",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
