---
name: Decrypt and Login to Kubernetes Cluster
description: |
    This action decrypts a base64-encoded, AES-256-CBC encrypted kubeconfig file
    and writes it to the kube config location, then verifies the current context
    and lists the nodes in the cluster.

inputs:
    encrypted_kubeconfig_base64:
        description: Base64-encoded encrypted kubeconfig
        required: true
    encryption_key:
        description: Encryption key to decrypt the kubeconfig
        required: true

runs:
    using: composite
    steps:
        - shell: bash
          run: |
              set -euo pipefail

              mkdir -p "$HOME/.kube"
              echo "${{ inputs.encrypted_kubeconfig_base64 }}" | base64 --decode > encrypted_kubeconfig.enc
              openssl enc -aes-256-cbc -d -in encrypted_kubeconfig.enc -out "$HOME/.kube/config" -pass pass:"${{ inputs.encryption_key }}" -pbkdf2
              rm encrypted_kubeconfig.enc
              chmod 600 "$HOME/.kube/config"

              kubectl config current-context
              kubectl get nodes
