package kubectlHelpers

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"multiregiontests/internal/helpers"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"github.com/gruntwork-io/terratest/modules/helm"
	http_helper "github.com/gruntwork-io/terratest/modules/http-helper"
	"github.com/gruntwork-io/terratest/modules/k8s"
	"github.com/gruntwork-io/terratest/modules/logger"
	"github.com/gruntwork-io/terratest/modules/shell"
	"github.com/stretchr/testify/require"
)

// basicAuthHeader returns the Authorization header for the Camunda basic-auth
// user. Sourced from CAMUNDA_BASIC_AUTH_USER and CAMUNDA_BASIC_AUTH_PASSWORD env
// vars (set in CI by internal-camunda-ci-credentials).
// It is evaluated lazily (not at package init) so test phases that never issue
// authenticated requests — e.g. kubeconfig generation during cluster prepare and
// cleanup — do not require these credentials. Panics if either is empty when an
// authenticated request is actually made — the publicly reachable CI cluster
// must never authenticate with demo:demo (see incident INC-5340).
func basicAuthHeader() string {
	user := os.Getenv("CAMUNDA_BASIC_AUTH_USER")
	password := os.Getenv("CAMUNDA_BASIC_AUTH_PASSWORD")
	if user == "" || password == "" {
		panic("CAMUNDA_BASIC_AUTH_USER and CAMUNDA_BASIC_AUTH_PASSWORD must be set (see INC-5340)")
	}
	return "Basic " + base64.StdEncoding.EncodeToString([]byte(user+":"+password))
}

var (
	// ElasticsearchPodName is the ECK-managed Elasticsearch pod used for exec operations (backup, restore, health checks).
	// Override via ELASTICSEARCH_POD_NAME env var.
	ElasticsearchPodName = helpers.GetEnv("ELASTICSEARCH_POD_NAME", "elasticsearch-es-masters-0")

	// ElasticsearchServiceName is the ECK-managed Elasticsearch headless service name used when rewriting
	// cross-region exporter URLs in camunda-values.yml placeholders. Must match the service name used by
	// generate_zeebe_helm_values.sh (which also reads ELASTICSEARCH_SERVICE_NAME).
	// Uses the headless service (not ClusterIP) so DNS returns pod IPs that are routable cross-cluster.
	// Override via ELASTICSEARCH_SERVICE_NAME env var.
	ElasticsearchServiceName = helpers.GetEnv("ELASTICSEARCH_SERVICE_NAME", "elasticsearch-es-masters")
)

// getElasticsearchPassword retrieves the elastic user password from the ECK-generated secret.
func getElasticsearchPassword(t *testing.T, kubectlOptions *k8s.KubectlOptions) string {
	t.Helper()

	// Read the elastic user's password through the kubectl binary rather than the
	// client-go API client (terratest's k8s.GetSecretE). On OpenShift the client-go
	// client performs a fresh API discovery against a very large API surface on every
	// call; under the ROSA control-plane load generated by failover/failback that
	// discovery can hang for many minutes (a kubectl exec on the same cluster keeps
	// working at the same moment), so retrying the client-go path just re-hangs. The
	// kubectl binary caches discovery and is what every exec-based Elasticsearch check
	// in this file uses successfully. Bound each attempt with --request-timeout and
	// retry so a transient stall is retried instead of fatal.
	const maxAttempts = 8
	for i := 0; i < maxAttempts; i++ {
		encoded, err := k8s.RunKubectlAndGetOutputE(
			t,
			kubectlOptions,
			"get", "secret", "elasticsearch-es-elastic-user",
			"-o", "jsonpath={.data.elastic}",
			"--request-timeout=60s",
		)
		if err != nil {
			t.Logf("[ES PASSWORD] failed to read secret (attempt %d/%d): %v", i+1, maxAttempts, err)
			time.Sleep(15 * time.Second)
			continue
		}

		decoded, derr := base64.StdEncoding.DecodeString(strings.TrimSpace(encoded))
		if derr != nil {
			t.Logf("[ES PASSWORD] failed to base64-decode secret (attempt %d/%d): %v", i+1, maxAttempts, derr)
			time.Sleep(15 * time.Second)
			continue
		}
		if len(decoded) == 0 {
			t.Logf("[ES PASSWORD] secret value empty (attempt %d/%d), retrying", i+1, maxAttempts)
			time.Sleep(15 * time.Second)
			continue
		}

		return string(decoded)
	}

	t.Fatalf("[ES PASSWORD] could not read elasticsearch-es-elastic-user secret after %d attempts", maxAttempts)
	return ""
}

type Partition struct {
	PartitionId int    `json:"partitionId"`
	Role        string `json:"role"`
	Health      string `json:"health"`
}

type Broker struct {
	NodeId     int         `json:"nodeId"`
	Host       string      `json:"host"`
	Port       int         `json:"port"`
	Partitions []Partition `json:"partitions"`
	Version    string      `json:"version"`
}

type ClusterInfo struct {
	Brokers           []Broker `json:"brokers"`
	ClusterSize       int      `json:"clusterSize"`
	PartitionsCount   int      `json:"partitionsCount"`
	ReplicationFactor int      `json:"replicationFactor"`
	GatewayVersion    string   `json:"gatewayVersion"`
}

type ElasticsearchClusterHealth struct {
	ClusterName string `json:"cluster_name"`
	Status      string `json:"status"`
	TimedOut    bool   `json:"timed_out"`
}

// NewServiceTunnelWithRetry establishes a port-forward tunnel to a Kubernetes Service with retry logic.
// Parameters:
//
//	t: *testing.T
//	kubectlOptions: target kubectl options
//	serviceName: name of the Service (must exist)
//	localPort: local port to bind (0 lets kubectl choose a random free port)
//	remotePort: target Service port
//	maxRetries: how many times to retry establishing the tunnel
//	backoff: sleep duration between retries
//
// Returns: (endpoint string, close func())
// runWithTimeout runs fn in a goroutine and returns its error, or a timeout error
// if it does not finish within timeout. terratest's k8s.Get* calls and port-forward
// setup have no client-side timeout, so a stalled cluster API server (observed on
// ROSA) otherwise blocks on the kernel TCP read timeout (~17 min). A goroutine left
// behind on timeout is harmless for a test process.
func runWithTimeout(timeout time.Duration, fn func() error) error {
	done := make(chan error, 1)
	go func() { done <- fn() }()
	select {
	case err := <-done:
		return err
	case <-time.After(timeout):
		return fmt.Errorf("operation timed out after %s", timeout)
	}
}

func NewServiceTunnelWithRetry(t *testing.T, kubectlOptions *k8s.KubectlOptions, serviceName string, localPort, remotePort, maxRetries int, backoff time.Duration) (string, func()) {
	t.Helper()

	if maxRetries < 1 {
		maxRetries = 1
	}
	if backoff <= 0 {
		backoff = 5 * time.Second
	}

	// Ensure the service exists, bounding/retrying the API read so a stalled cluster
	// API server fails fast and is retried instead of blocking the kernel TCP timeout.
	serviceReady := false
	for i := 0; i < maxRetries; i++ {
		err := runWithTimeout(60*time.Second, func() error {
			svc, e := k8s.GetServiceE(t, kubectlOptions, serviceName)
			if e != nil {
				return e
			}
			if svc.Name != serviceName {
				return fmt.Errorf("unexpected service name %q", svc.Name)
			}
			return nil
		})
		if err == nil {
			serviceReady = true
			break
		}
		t.Logf("[TUNNEL] get service %s (ns %s) failed (attempt %d/%d): %v", serviceName, kubectlOptions.Namespace, i+1, maxRetries, err)
		if i < maxRetries-1 {
			time.Sleep(backoff)
		}
	}
	if !serviceReady {
		t.Fatalf("[TUNNEL] service %s (ns %s) not reachable after %d attempts", serviceName, kubectlOptions.Namespace, maxRetries)
		return "", func() {}
	}

	// Establish the port-forward with a fresh tunnel per attempt (a hung attempt is
	// abandoned rather than reused) and bound each attempt so it cannot block forever.
	var endpoint string
	cleanup := func() {}
	established := false
	for i := 0; i < maxRetries; i++ {
		tunnel := k8s.NewTunnel(kubectlOptions, k8s.ResourceTypeService, serviceName, localPort, remotePort)
		err := runWithTimeout(90*time.Second, func() error { return tunnel.ForwardPortE(t) })
		if err == nil {
			endpoint = tunnel.Endpoint()
			tnl := tunnel
			cleanup = func() { tnl.Close() }
			established = true
			break
		}
		t.Logf("[TUNNEL] port-forward attempt %d/%d failed for %s:%d -> %s: %v", i+1, maxRetries, serviceName, remotePort, kubectlOptions.Namespace, err)
		if i < maxRetries-1 {
			time.Sleep(backoff)
		}
	}
	if !established {
		t.Fatalf("[TUNNEL] failed to establish port-forward to %s after %d attempts", serviceName, maxRetries)
		return "", func() {}
	}

	return endpoint, cleanup
}

func CrossClusterCommunication(t *testing.T, withDNS bool, k8sManifests string, primary, secondary helpers.Cluster, kubeConfigPrimary, kubeConfigSecondary string) {
	kubeResourcePath := fmt.Sprintf("%s/%s", k8sManifests, "nginx.yml")

	if withDNS {
		primaryNamespaceArr := strings.Split(helpers.GetEnv("CLUSTER_0_NAMESPACE_ARR", ""), ",")
		secondaryNamespaceArr := strings.Split(helpers.GetEnv("CLUSTER_1_NAMESPACE_ARR", ""), ",")
		for i := 0; i < len(primaryNamespaceArr); i++ {
			os.Setenv("CLUSTER_0", primary.ClusterName)
			os.Setenv("CAMUNDA_NAMESPACE_0", primaryNamespaceArr[i])
			os.Setenv("CLUSTER_1", secondary.ClusterName)
			os.Setenv("CAMUNDA_NAMESPACE_1", secondaryNamespaceArr[i])
			os.Setenv("KUBECONFIG", kubeConfigPrimary+":"+kubeConfigSecondary)

			output := shell.RunCommandAndGetOutput(t, shell.Command{
				Command: "sh",
				Args: []string{
					"../procedure/test_dns_chaining.sh",
				},
			})

			// Check the output for success or failure messages
			if strings.Contains(output, "Failed to reach the target instance") {
				t.Fatalf("Script failed: %s", output)
			} else {
				t.Logf("Script output: %s", output)
			}
		}

	} else {
		// Check if the pods can reach each other via the IPs directly

		defer k8s.KubectlDelete(t, &primary.KubectlNamespace, kubeResourcePath)
		defer k8s.KubectlDelete(t, &secondary.KubectlNamespace, kubeResourcePath)

		k8s.KubectlApply(t, &primary.KubectlNamespace, kubeResourcePath)
		k8s.KubectlApply(t, &secondary.KubectlNamespace, kubeResourcePath)

		k8s.WaitUntilServiceAvailable(t, &primary.KubectlNamespace, "sample-nginx-peer", 10, 5*time.Second)
		k8s.WaitUntilServiceAvailable(t, &secondary.KubectlNamespace, "sample-nginx-peer", 10, 5*time.Second)

		k8s.WaitUntilPodAvailable(t, &primary.KubectlNamespace, "sample-nginx", 10, 5*time.Second)
		k8s.WaitUntilPodAvailable(t, &secondary.KubectlNamespace, "sample-nginx", 10, 5*time.Second)

		podPrimary := k8s.GetPod(t, &primary.KubectlNamespace, "sample-nginx")
		podSecondary := k8s.GetPod(t, &secondary.KubectlNamespace, "sample-nginx")

		podPrimaryIP := podPrimary.Status.PodIP
		require.NotEmpty(t, podPrimaryIP)

		podSecondaryIP := podSecondary.Status.PodIP
		require.NotEmpty(t, podSecondaryIP)

		k8s.RunKubectl(t, &primary.KubectlNamespace, "exec", podPrimary.Name, "--", "curl", "--max-time", "15", podSecondaryIP)
		k8s.RunKubectl(t, &secondary.KubectlNamespace, "exec", podSecondary.Name, "--", "curl", "--max-time", "15", podPrimaryIP)

		t.Log("[CROSS CLUSTER COMMUNICATION] Communication established")
	}
}

func CheckCoreDNSReload(t *testing.T, kubectlOptions *k8s.KubectlOptions) {
	pods := k8s.ListPods(t, kubectlOptions, metav1.ListOptions{LabelSelector: "k8s-app=kube-dns"})

	for _, pod := range pods {
		reloaded := false
		for i := 0; i < 12; i++ {
			t.Logf("[COREDNS RELOAD] Checking CoreDNS logs for pod %s (attempt %d/12)", pod.Name, i+1)
			logs := k8s.GetPodLogs(t, kubectlOptions, &pod, "coredns")

			if strings.Contains(logs, "Reloading complete") {
				t.Log("[COREDNS RELOAD] CoreDNS reloaded successfully")
				reloaded = true
				break
			}
			t.Log("[COREDNS RELOAD] CoreDNS not reloaded yet. Waiting...")
			time.Sleep(15 * time.Second)
		}
		require.True(t, reloaded, "[COREDNS RELOAD] CoreDNS did not reload after 12 attempts for pod %s", pod.Name)
	}
}

func TeardownC8Helm(t *testing.T, kubectlOptions *k8s.KubectlOptions) {
	helmOptions := &helm.Options{
		KubectlOptions: kubectlOptions,
	}

	helm.Delete(t, helmOptions, "camunda", true)

	// Delete ECK-managed Elasticsearch CR before PVCs to avoid stuck finalizers.
	// The Elasticsearch CR is deployed outside of Helm via kubectl apply, so helm delete does not remove it.
	t.Logf("[C8 HELM TEARDOWN] deleting ECK Elasticsearch CR in namespace %s", kubectlOptions.Namespace)
	k8s.RunKubectl(t, kubectlOptions, "delete", "elasticsearch", "--all", "--timeout=120s", "--ignore-not-found=true")

	t.Logf("[C8 HELM TEARDOWN] removing all PVCs and PVs from namespace %s", kubectlOptions.Namespace)

	pvcs := k8s.ListPersistentVolumeClaims(t, kubectlOptions, metav1.ListOptions{})

	for _, pvc := range pvcs {
		k8s.RunKubectl(t, kubectlOptions, "delete", "pvc", pvc.Name, "--ignore-not-found=true")
	}
}

func CheckOperateForProcesses(t *testing.T, cluster helpers.Cluster, tenantId string) {
	t.Logf("[C8 PROCESS] Checking for Cluster %s whether Operate contains deployed processes", cluster.ClusterName)

	endpoint, closeFn := NewServiceTunnelWithRetry(t, &cluster.KubectlNamespace, "camunda-zeebe-gateway", 0, 8080, 5, 15*time.Second)
	defer closeFn()

	// create http client
	client := &http.Client{}

	// Prepare request body with tenantId if provided
	var instanceRequestBody string
	if tenantId != "" {
		instanceRequestBody = fmt.Sprintf(`{"filter": { "tenantId":"%s" }}`, tenantId)
	} else {
		instanceRequestBody = `{}`
	}

	var bodyString string
	for i := 0; i < 8; i++ {
		// fresh request each iteration to avoid reusing consumed body
		req, err := http.NewRequest("POST", fmt.Sprintf("http://%s/v2/process-definitions/search", endpoint), strings.NewReader(instanceRequestBody))
		if err != nil {
			t.Fatalf("[C8 PROCESS] %s", err)
			return
		}
		req.Header.Add("Content-Type", "application/json")
		req.Header.Add("Authorization", basicAuthHeader())

		res, err := client.Do(req)
		if err != nil {
			t.Fatalf("[C8 PROCESS] %s", err)
			return
		}

		body, err := io.ReadAll(res.Body)
		closeErr := res.Body.Close()
		if err != nil {
			t.Fatalf("[C8 PROCESS] %s", err)
			return
		}
		if closeErr != nil {
			t.Fatalf("[C8 PROCESS] close body: %v", closeErr)
			return
		}

		bodyString = string(body)

		t.Logf("[C8 Process] %s", bodyString)
		if !strings.Contains(bodyString, "\"total\":0") {
			t.Log("[C8 PROCESS] processes are present, breaking and asserting")
			break
		}
		t.Log("[C8 PROCESS] not imported yet, waiting...")
		time.Sleep(15 * time.Second)
	}

	require.Contains(t, bodyString, "Big variable process")
	require.Contains(t, bodyString, "bigVarProcess")
}

func CheckOperateForProcessInstances(t *testing.T, cluster helpers.Cluster, size int, tenantId string) {

	t.Logf("[C8 PROCESS INSTANCES] Checking for Cluster %s whether instances of bigVarProcess are created", cluster.ClusterName)

	endpoint, closeFn := NewServiceTunnelWithRetry(t, &cluster.KubectlNamespace, "camunda-zeebe-gateway", 0, 8080, 5, 10*time.Second)
	defer closeFn()

	// create http client
	client := &http.Client{}

	// Prepare request body with tenantId if provided
	var instanceRequestBody string
	if tenantId != "" {
		instanceRequestBody = fmt.Sprintf(`{"filter": { "tenantId":"%s" }}`, tenantId)
	} else {
		instanceRequestBody = `{}`
	}

	expectedTotal := fmt.Sprintf("\"totalItems\":%d", size)

	var bodyString string
	for i := 0; i < 20; i++ {
		// fresh request each iteration to avoid reusing consumed body
		req, err := http.NewRequest("POST", fmt.Sprintf("http://%s/v2/process-instances/search", endpoint), strings.NewReader(instanceRequestBody))
		if err != nil {
			t.Fatalf("[C8 PROCESS INSTANCES] %s", err)
			return
		}
		req.Header.Add("Content-Type", "application/json")
		req.Header.Add("Authorization", basicAuthHeader())

		res, err := client.Do(req)
		if err != nil {
			t.Fatalf("[C8 PROCESS INSTANCES] %s", err)
			return
		}

		body, err := io.ReadAll(res.Body)
		closeErr := res.Body.Close()
		if err != nil {
			t.Fatalf("[C8 PROCESS INSTANCES] %s", err)
			return
		}
		if closeErr != nil {
			t.Fatalf("[C8 PROCESS INSTANCES] close body: %v", closeErr)
			return
		}

		bodyString = string(body)

		t.Logf("[C8 Process INSTANCES] %s", bodyString)
		if strings.Contains(bodyString, expectedTotal) {
			t.Logf("[C8 PROCESS INSTANCES] expected %d instances found, breaking", size)
			break
		}
		t.Logf("[C8 PROCESS INSTANCES] expected %d instances not yet reached, waiting...", size)
		time.Sleep(15 * time.Second)
	}

	require.Contains(t, bodyString, "Big variable process")
	require.Contains(t, bodyString, "bigVarProcess")
	require.Contains(t, bodyString, fmt.Sprintf("\"totalItems\":%d", size))
}

func RunSensitiveKubectlCommand(t *testing.T, kubectlOptions *k8s.KubectlOptions, command ...string) {
	defer func() {
		kubectlOptions.Logger = nil
	}()
	kubectlOptions.Logger = logger.Discard
	k8s.RunKubectl(t, kubectlOptions, command...)
}

func ConfigureElasticBackup(t *testing.T, cluster helpers.Cluster, backupBucket, inputVersion string) {
	t.Logf("[ELASTICSEARCH] Configuring Elasticsearch backup for cluster %s", cluster.ClusterName)

	esPassword := getElasticsearchPassword(t, &cluster.KubectlNamespace)

	// Replace dots with dashes in the version string.
	version := strings.ReplaceAll(inputVersion, ".", "-")

	output, err := k8s.RunKubectlAndGetOutputE(t, &cluster.KubectlNamespace, "exec", ElasticsearchPodName, "--",
		"curl", "-u", fmt.Sprintf("elastic:%s", esPassword), "-XPUT", "http://localhost:9200/_snapshot/camunda_backup",
		"-H", "Content-Type: application/json",
		"-d", fmt.Sprintf("{\"type\": \"s3\", \"settings\": {\"bucket\": \"%s\", \"client\": \"camunda\", \"base_path\": \"%s/%s-backups\"}}",
			backupBucket, backupBucket, version))

	if err != nil {
		t.Fatalf("[ELASTICSEARCH] Error: %s", err)
		return
	}

	if !strings.Contains(output, "acknowledged") {
		t.Fatalf("[ELASTICSEARCH] Error: %s", output)
		return
	}

	require.Contains(t, output, "acknowledged")
	t.Logf("[ELASTICSEARCH] Success: %s", output)
}

func CreateElasticBackup(t *testing.T, cluster helpers.Cluster, backupName string) {
	t.Logf("[ELASTICSEARCH BACKUP] Creating Elasticsearch backup for cluster %s", cluster.ClusterName)

	esPassword := getElasticsearchPassword(t, &cluster.KubectlNamespace)

	// Delete any pre-existing snapshot with the same name to avoid snapshot_name_already_in_use_exception
	k8s.RunKubectlAndGetOutputE(t, &cluster.KubectlNamespace, "exec", ElasticsearchPodName, "--", "curl", "-u", fmt.Sprintf("elastic:%s", esPassword), "-X", "DELETE", fmt.Sprintf("localhost:9200/_snapshot/camunda_backup/%s", backupName))

	output, err := k8s.RunKubectlAndGetOutputE(t, &cluster.KubectlNamespace, "exec", ElasticsearchPodName, "--", "curl", "-u", fmt.Sprintf("elastic:%s", esPassword), "-X", "PUT", fmt.Sprintf("localhost:9200/_snapshot/camunda_backup/%s?wait_for_completion=true", backupName), "-H", "Content-Type: application/json", "-d", `{"include_global_state":true}`)
	if err != nil {
		t.Fatalf("[ELASTICSEARCH BACKUP] %s", err)
		return
	}

	require.Contains(t, output, "\"failed\":0")
	t.Logf("[ELASTICSEARCH BACKUP] Created backup: %s", output)
}

func CheckThatElasticBackupIsPresent(t *testing.T, cluster helpers.Cluster, backupName, backupBucket, remoteChartVersion string) {
	t.Logf("[ELASTICSEARCH BACKUP] Checking that Elasticsearch backup is present for cluster %s", cluster.ClusterName)

	output := ""
	var err error

	for i := 0; i < 3; i++ {
		output, err = getAllElasticBackups(t, cluster)
		if err == nil && output != "" {
			break
		}
		removeElasticBackup(t, cluster)
		time.Sleep(5 * time.Second)
		ConfigureElasticBackup(t, cluster, backupBucket, remoteChartVersion)
		time.Sleep(5 * time.Second)
	}

	require.Contains(t, output, backupName)
	t.Logf("[ELASTICSEARCH BACKUP] Backup present: %s", output)
}

func removeElasticBackup(t *testing.T, cluster helpers.Cluster) {
	t.Logf("[ELASTICSEARCH BACKUP] Backup not found, removing backup store to recreate %s", cluster.ClusterName)

	esPassword := getElasticsearchPassword(t, &cluster.KubectlNamespace)

	k8s.RunKubectl(t, &cluster.KubectlNamespace, "exec", ElasticsearchPodName, "--", "curl", "-u", fmt.Sprintf("elastic:%s", esPassword), "-XDELETE", "localhost:9200/_snapshot/camunda_backup")
}

func getAllElasticBackups(t *testing.T, cluster helpers.Cluster) (string, error) {
	esPassword := getElasticsearchPassword(t, &cluster.KubectlNamespace)

	output, err := k8s.RunKubectlAndGetOutputE(t, &cluster.KubectlNamespace, "exec", ElasticsearchPodName, "--", "curl", "-u", fmt.Sprintf("elastic:%s", esPassword), "-XGET", "localhost:9200/_snapshot/camunda_backup/_all")
	if err != nil {
		t.Fatalf("[ELASTICSEARCH BACKUP] %s", err)
		return "", err
	}

	return output, nil
}

func RestoreElasticBackup(t *testing.T, cluster helpers.Cluster, backupName string) {
	t.Logf("[ELASTICSEARCH BACKUP] Restoring Elasticsearch backup for cluster %s", cluster.ClusterName)

	esPassword := getElasticsearchPassword(t, &cluster.KubectlNamespace)

	output, err := k8s.RunKubectlAndGetOutputE(t, &cluster.KubectlNamespace, "exec", ElasticsearchPodName, "--", "curl", "-u", fmt.Sprintf("elastic:%s", esPassword), "-XPOST", fmt.Sprintf("localhost:9200/_snapshot/camunda_backup/%s/_restore?wait_for_completion=true", backupName), "-H", "Content-Type: application/json", "-d", `{"include_global_state":true}`)
	if err != nil {
		t.Fatalf("[ELASTICSEARCH BACKUP] %s", err)
		return
	}

	require.Contains(t, output, "\"failed\":0")
	t.Logf("[ELASTICSEARCH BACKUP] Restored backup: %s", output)

}

func InstallUpgradeC8Helm(t *testing.T, kubectlOptions *k8s.KubectlOptions, remoteChartVersion, remoteChartName, remoteChartSource, namespace0, namespace1 string, valuesYamlFiles []string, region int, setValues, setStringValues map[string]string) {

	if !helpers.IsTeleportEnabled() {
		// Set environment variables for the script
		os.Setenv("CAMUNDA_NAMESPACE_0", namespace0)
		os.Setenv("CAMUNDA_NAMESPACE_1", namespace1)
		os.Setenv("CAMUNDA_RELEASE_NAME", "camunda")
		os.Setenv("ZEEBE_CLUSTER_SIZE", "8")
	}

	// Run the script and capture its output
	cmd := exec.Command("bash", "-c", "../procedure/generate_zeebe_helm_values.sh")
	output, err := cmd.Output()
	if err != nil {
		t.Fatalf("[C8 HELM] Error running script: %v\n", err)
		return
	}

	// Convert byte slice to string
	scriptOutput := string(output)

	// Extract the replacement text for the initial contact points and Elasticsearch URLs
	initialContact := extractReplacementText(scriptOutput, "CAMUNDA_CLUSTER_INITIALCONTACTPOINTS")
	elastic0 := extractReplacementText(scriptOutput, "CAMUNDA_DATA_EXPORTERS_CAMUNDAREGION0_ARGS_CONNECT_URL")
	elastic1 := extractReplacementText(scriptOutput, "CAMUNDA_DATA_EXPORTERS_CAMUNDAREGION1_ARGS_CONNECT_URL")

	require.NotEmpty(t, initialContact, "Initial contact points should not be empty")
	require.NotEmpty(t, elastic0, "Elasticsearch region 0 URL should not be empty")
	require.NotEmpty(t, elastic1, "Elasticsearch region 1 URL should not be empty")

	valuesFiles := valuesYamlFiles

	if helpers.IsTeleportEnabled() {
		valuesFiles = append(valuesFiles, "./fixtures/teleport-affinities-tolerations.yml")
	}

	filePath := valuesFiles[0]

	content, err := os.ReadFile(filePath)
	if err != nil {
		t.Fatalf("[C8 HELM] Error reading file: %v\n", err)
		return
	}

	// Convert byte slice to string
	fileContent := string(content)

	// Replace the placeholders with the replacement strings
	modifiedContent := strings.Replace(fileContent, "PLACEHOLDER", initialContact, -1)
	modifiedContent = strings.Replace(modifiedContent, fmt.Sprintf("http://%s.camunda-primary.svc.cluster.local:9200", ElasticsearchServiceName), elastic0, -1)
	modifiedContent = strings.Replace(modifiedContent, fmt.Sprintf("http://%s.camunda-secondary.svc.cluster.local:9200", ElasticsearchServiceName), elastic1, -1)

	// Write the modified content back to the file
	err = os.WriteFile(filePath, []byte(modifiedContent), 0644)
	if err != nil {
		t.Fatalf("[C8 HELM] Error writing file: %v\n", err)
		return
	}

	helmOptions := &helm.Options{
		KubectlOptions: kubectlOptions,
		Version:        remoteChartVersion,
		ValuesFiles:    valuesFiles,
		SetValues:      setValues,
		SetStrValues:   setStringValues,
	}

	if !strings.HasPrefix(remoteChartName, "oci://") {
		helm.AddRepo(t, helmOptions, "camunda", remoteChartSource)
	}

	// Terratest is actively ignoring the version in an upgrade
	helmOptions.ExtraArgs = map[string][]string{
		"upgrade": {"--version", remoteChartVersion, "--install"},
	}

	// Write the final merged values to a debug file for troubleshooting
	writeDebugValues(t, valuesFiles, setValues, setStringValues)

	helm.Upgrade(t, helmOptions, remoteChartName, "camunda")

	// Write the old file back to the file - mostly for local development
	err = os.WriteFile(filePath, []byte(fileContent), 0644)
	if err != nil {
		t.Fatalf("[C8 HELM] Error writing file: %v\n", err)
		return
	}
}
func extractReplacementText(output, variableName string) string {
	startMarker := fmt.Sprintf("- name: %s\n  value: ", variableName)
	startIndex := strings.Index(output, startMarker)
	if startIndex == -1 {
		return ""
	}
	startIndex += len(startMarker)
	endIndex := strings.Index(output[startIndex:], "\n")
	if endIndex == -1 {
		return output[startIndex:]
	}
	return output[startIndex : startIndex+endIndex]
}

func writeDebugValues(t *testing.T, valuesFiles []string, setValues, setStringValues map[string]string) {
	debugDir := "debug"
	if err := os.MkdirAll(debugDir, 0755); err != nil {
		t.Logf("[C8 HELM DEBUG] Failed to create debug directory: %v", err)
		return
	}

	var combined strings.Builder

	for _, f := range valuesFiles {
		combined.WriteString(fmt.Sprintf("# --- Source: %s ---\n", f))
		content, err := os.ReadFile(f)
		if err != nil {
			combined.WriteString(fmt.Sprintf("# Error reading file: %v\n", err))
		} else {
			combined.Write(content)
			combined.WriteString("\n")
		}
	}

	if len(setValues) > 0 {
		combined.WriteString("# --- Helm --set values ---\n")
		for k, v := range setValues {
			combined.WriteString(fmt.Sprintf("# %s=%s\n", k, v))
		}
	}

	if len(setStringValues) > 0 {
		combined.WriteString("# --- Helm --set-string values ---\n")
		for k, v := range setStringValues {
			combined.WriteString(fmt.Sprintf("# %s=%s\n", k, v))
		}
	}

	debugFile := filepath.Join(debugDir, "values.yaml")
	if err := os.WriteFile(debugFile, []byte(combined.String()), 0644); err != nil {
		t.Logf("[C8 HELM DEBUG] Failed to write debug values: %v", err)
		return
	}

	t.Logf("[C8 HELM DEBUG] Final values written to %s", debugFile)
}

func StatefulSetContains(t *testing.T, kubectlOptions *k8s.KubectlOptions, statefulset, searchValue string) bool {
	t.Logf("[STATEFULSET] Checking whether StatefulSet %s contains %s", statefulset, searchValue)

	// Temporarily disable logging
	// Output might be too large
	defer func() {
		kubectlOptions.Logger = nil
	}()
	kubectlOptions.Logger = logger.Discard

	output, err := k8s.RunKubectlAndGetOutputE(t, kubectlOptions, "get", "statefulset", statefulset, "-o", "yaml")
	if err != nil {
		t.Fatalf("[STATEFULSET] %s", err)
		return false
	}

	val := strings.Contains(output, searchValue)
	t.Logf("[STATEFULSET] StatefulSet %s contains %s: %t", statefulset, searchValue, val)

	return val
}

func GetZeebeBrokerId(t *testing.T, kubectlOptions *k8s.KubectlOptions, podName string) int {
	t.Logf("[ZEEBE BROKER ID] Getting Zeebe Broker ID for pod %s", podName)

	defer func() {
		kubectlOptions.Logger = nil
	}()
	kubectlOptions.Logger = logger.Discard

	// The broker pod runs a wait-clusterset-dns init container alongside the
	// orchestration container; pin kubectl exec to the app container so the
	// "Defaulted container" notice does not pollute the captured output.
	output, err := k8s.RunKubectlAndGetOutputE(t, kubectlOptions, "exec", podName, "-c", "orchestration", "--", "pgrep", "java")
	if err != nil {
		t.Fatalf("[ZEEBE BROKER ID] %s", err)
		return -1
	}

	output, err = k8s.RunKubectlAndGetOutputE(t, kubectlOptions, "exec", podName, "-c", "orchestration", "--", "cat", fmt.Sprintf("/proc/%s/environ", output))
	if err != nil {
		t.Fatalf("[ZEEBE BROKER ID] %s", err)
		return -1
	}

	return helpers.CutOutString(output, "ORCHESTRATION_NODE_ID=[0-9]")
}

func CheckC8RunningProperly(t *testing.T, primary helpers.Cluster, namespace0, namespace1 string) {
	topology := GetClusterTopology(t, &primary.KubectlNamespace)

	require.Equal(t, 8, len(topology.Brokers))

	primaryCount := 0
	secondaryCount := 0

	t.Log("[C8 CHECK] Cluster status:")
	for _, broker := range topology.Brokers {
		if strings.Contains(broker.Host, namespace0) {
			primaryCount++
		} else if strings.Contains(broker.Host, namespace1) {
			secondaryCount++
		}
		t.Logf("[C8 CHECK] Broker ID: %d, Address: %s, Partitions: %v\n", broker.NodeId, broker.Host, broker.Partitions)
	}

	require.Equal(t, 4, primaryCount)
	require.Equal(t, 4, secondaryCount)
}

func DeployC8processAndCheck(t *testing.T, kubectlOptions helpers.Cluster, resourceDir, tenantId string) {
	// Deploy the BPMN process using the shared deployment function
	bpmnFilePath := fmt.Sprintf("%s/single-task.bpmn", resourceDir)
	DeployBpmnProcess(t, &kubectlOptions.KubectlNamespace, bpmnFilePath, tenantId, "bigVarProcess")

	t.Log("[C8 PROCESS] Sleeping shortly to let process be propagated")
	time.Sleep(15 * time.Second)

	// Start process instances
	StartProcessInstances(t, &kubectlOptions.KubectlNamespace, "bigVarProcess", tenantId, 6)

	t.Log("[C8 PROCESS] Sleeping shortly to let instances be propagated")
	time.Sleep(15 * time.Second)
}

// StartProcessInstances starts process instances for the given process definition.
func StartProcessInstances(t *testing.T, kubectlOptions *k8s.KubectlOptions, processDefinitionId, tenantId string, count int) {
	t.Helper()

	endpoint, closeFn := NewServiceTunnelWithRetry(t, kubectlOptions, "camunda-zeebe-gateway", 0, 8080, 5, 10*time.Second)
	defer closeFn()

	for i := 1; i <= count; i++ {
		t.Logf("[C8 PROCESS] Starting Process instance %d/%d 🚀", i, count)

		// Prepare request body with tenantId if provided
		var instanceRequestBody string
		if tenantId != "" {
			instanceRequestBody = fmt.Sprintf(`{"processDefinitionId":"%s","tenantId":"%s"}`, processDefinitionId, tenantId)
		} else {
			instanceRequestBody = fmt.Sprintf(`{"processDefinitionId":"%s"}`, processDefinitionId)
		}

		code, resBody := http_helper.HTTPDoWithOptions(t, http_helper.HttpDoOptions{
			Method: "POST",
			Url:    fmt.Sprintf("http://%s/v2/process-instances", endpoint),
			Body:   strings.NewReader(instanceRequestBody),
			Headers: map[string]string{
				"Content-Type":  "application/json",
				"Accept":        "application/json",
				"Authorization": basicAuthHeader(),
			},
			TlsConfig: nil,
			Timeout:   30,
		})
		if code != 200 {
			t.Fatalf("[C8 PROCESS] Failed to start process instance (%d): %s", i, resBody)
			return
		}
		t.Logf("[C8 PROCESS] Created process instance %d: %s", i, resBody)
		require.NotEmpty(t, resBody)
		require.Contains(t, resBody, processDefinitionId)
	}
}

// DeployBpmnProcess deploys a BPMN file to Zeebe via the gateway REST API.
func DeployBpmnProcess(t *testing.T, kubectlOptions *k8s.KubectlOptions, bpmnFilePath, tenantId, expectedProcessId string) string {
	t.Helper()

	endpoint, closeFn := NewServiceTunnelWithRetry(t, kubectlOptions, "camunda-zeebe-gateway", 0, 8080, 5, 10*time.Second)
	defer closeFn()

	file, err := os.Open(bpmnFilePath)
	if err != nil {
		t.Fatalf("[BPMN DEPLOY] can't open file %s - %s", bpmnFilePath, err)
		return ""
	}
	defer file.Close()

	reqBody := &bytes.Buffer{}
	writer := multipart.NewWriter(reqBody)

	part, err := writer.CreateFormFile("resources", filepath.Base(file.Name()))
	if err != nil {
		t.Fatalf("[BPMN DEPLOY] can't create form file - %s", err)
		return ""
	}

	_, err = io.Copy(part, file)
	if err != nil {
		t.Fatalf("[BPMN DEPLOY] can't copy file - %s", err)
		return ""
	}

	// Add tenantId field if provided
	if tenantId != "" {
		err = writer.WriteField("tenantId", tenantId)
		if err != nil {
			t.Fatalf("[BPMN DEPLOY] can't write tenantId field - %s", err)
			return ""
		}
	}

	err = writer.Close()
	if err != nil {
		t.Fatalf("[BPMN DEPLOY] can't close writer - %s", err)
		return ""
	}

	code, resBody := http_helper.HTTPDoWithOptions(t, http_helper.HttpDoOptions{
		Method: "POST",
		Url:    fmt.Sprintf("http://%s/v2/deployments", endpoint),
		Body:   reqBody,
		Headers: map[string]string{
			"Content-Type":  writer.FormDataContentType(),
			"Accept":        "application/json",
			"Authorization": basicAuthHeader(),
		},
		TlsConfig: nil,
		Timeout:   30,
	})
	if code != 200 {
		t.Fatalf("[BPMN DEPLOY] Failed to deploy process: %s", resBody)
		return ""
	}

	t.Logf("[BPMN DEPLOY] Created process: %s", resBody)
	if expectedProcessId != "" {
		require.Contains(t, resBody, expectedProcessId)
	}

	return resBody
}

func DumpAllPodLogs(t *testing.T, kubectlOptions *k8s.KubectlOptions) {
	t.Logf("[POD LOGS] Dumping logs for namespace %s", kubectlOptions.Namespace)

	// Temporarily disable logging to not overflow with all logs
	defer func() {
		kubectlOptions.Logger = nil
	}()
	kubectlOptions.Logger = logger.Discard

	pods := k8s.ListPods(t, kubectlOptions, metav1.ListOptions{})

	for _, pod := range pods {
		t.Logf("[POD LOGS] Found pod %s", pod.Name)

		type containerInfo struct {
			name          string
			containerType string
		}
		var allContainers []containerInfo

		for _, container := range pod.Spec.InitContainers {
			t.Logf("[POD LOGS] Found init container %s in pod %s", container.Name, pod.Name)

			allContainers = append(allContainers, containerInfo{
				name:          container.Name,
				containerType: "init",
			})
		}

		for _, container := range pod.Spec.Containers {
			t.Logf("[POD LOGS] Found container %s in pod %s", container.Name, pod.Name)
			allContainers = append(allContainers, containerInfo{
				name:          container.Name,
				containerType: "",
			})
		}

		for _, container := range allContainers {
			t.Logf("[POD LOGS] Dumping logs for %s container %s in pod %s", container.containerType, container.name, pod.Name)

			podLogs, err := k8s.GetPodLogsE(t, kubectlOptions, &pod, container.name)
			if err != nil {
				t.Fatalf("Error getting pod logs: %v", err)
			}

			// Write logs to a file
			err = os.WriteFile(fmt.Sprintf("%s-%s-%s-%s.log", kubectlOptions.Namespace, pod.Name, container.containerType, container.name), []byte(podLogs), 0644)
			if err != nil {
				t.Fatalf("Error writing logs to file: %v", err)
			}
		}
	}
}

// CreateTenant creates a tenant via the Camunda API
func CreateTenant(t *testing.T, cluster helpers.Cluster, tenantId, name, description string) {
	t.Logf("[TENANT] Creating tenant '%s' in cluster %s", tenantId, cluster.ClusterName)

	endpoint, closeFn := NewServiceTunnelWithRetry(t, &cluster.KubectlNamespace, "camunda-zeebe-gateway", 0, 8080, 5, 10*time.Second)
	defer closeFn()

	// Prepare request body
	requestBody := fmt.Sprintf(`{
  "tenantId": "%s",
  "name": "%s",
  "description": "%s"
}`, tenantId, name, description)

	client := &http.Client{Timeout: 30 * time.Second}
	req, err := http.NewRequest("POST", fmt.Sprintf("http://%s/v2/tenants", endpoint), strings.NewReader(requestBody))
	if err != nil {
		t.Fatalf("[TENANT] Failed to create request: %v", err)
		return
	}

	req.Header.Add("Content-Type", "application/json")
	req.Header.Add("Accept", "application/json")
	req.Header.Add("Authorization", basicAuthHeader())

	res, err := client.Do(req)
	if err != nil {
		t.Fatalf("[TENANT] Failed to create tenant: %v", err)
		return
	}

	body, err := io.ReadAll(res.Body)
	closeErr := res.Body.Close()
	if err != nil {
		t.Fatalf("[TENANT] Failed to read response: %v", err)
		return
	}
	if closeErr != nil {
		t.Fatalf("[TENANT] Failed to close body: %v", closeErr)
		return
	}

	if res.StatusCode != 200 && res.StatusCode != 201 {
		t.Fatalf("[TENANT] Failed to create tenant (status %d): %s", res.StatusCode, string(body))
		return
	}

	t.Logf("[TENANT] Successfully created tenant: %s", string(body))
	require.Contains(t, string(body), tenantId)
}

// AssignRoleToTenant assigns a role to a tenant via the Camunda API
func AssignRoleToTenant(t *testing.T, cluster helpers.Cluster, tenantId, roleID string) {
	t.Logf("[TENANT] Assigning role '%s' to tenant '%s' in cluster %s", roleID, tenantId, cluster.ClusterName)

	endpoint, closeFn := NewServiceTunnelWithRetry(t, &cluster.KubectlNamespace, "camunda-zeebe-gateway", 0, 8080, 5, 10*time.Second)
	defer closeFn()

	client := &http.Client{Timeout: 30 * time.Second}
	req, err := http.NewRequest("PUT", fmt.Sprintf("http://%s/v2/tenants/%s/roles/%s", endpoint, tenantId, roleID), nil)
	if err != nil {
		t.Fatalf("[TENANT] Failed to create request: %v", err)
		return
	}

	req.Header.Add("Authorization", basicAuthHeader())

	res, err := client.Do(req)
	if err != nil {
		t.Fatalf("[TENANT] Failed to assign role: %v", err)
		return
	}

	body, err := io.ReadAll(res.Body)
	closeErr := res.Body.Close()
	if err != nil {
		t.Fatalf("[TENANT] Failed to read response: %v", err)
		return
	}
	if closeErr != nil {
		t.Fatalf("[TENANT] Failed to close body: %v", closeErr)
		return
	}

	if res.StatusCode != 200 && res.StatusCode != 204 {
		t.Fatalf("[TENANT] Failed to assign role (status %d): %s", res.StatusCode, string(body))
		return
	}

	t.Logf("[TENANT] Successfully assigned role '%s' to tenant '%s'", roleID, tenantId)
}

// CheckTenantExists verifies that a tenant exists via the Camunda API
func CheckTenantExists(t *testing.T, cluster helpers.Cluster, tenantId string) {
	t.Logf("[TENANT] Checking if tenant '%s' exists in cluster %s", tenantId, cluster.ClusterName)

	endpoint, closeFn := NewServiceTunnelWithRetry(t, &cluster.KubectlNamespace, "camunda-zeebe-gateway", 0, 8080, 5, 10*time.Second)
	defer closeFn()

	client := &http.Client{Timeout: 30 * time.Second}
	req, err := http.NewRequest("GET", fmt.Sprintf("http://%s/v2/tenants/%s", endpoint, tenantId), nil)
	if err != nil {
		t.Fatalf("[TENANT] Failed to create request: %v", err)
		return
	}

	req.Header.Add("Accept", "application/json")
	req.Header.Add("Authorization", basicAuthHeader())

	res, err := client.Do(req)
	if err != nil {
		t.Fatalf("[TENANT] Failed to check tenant: %v", err)
		return
	}

	body, err := io.ReadAll(res.Body)
	closeErr := res.Body.Close()
	if err != nil {
		t.Fatalf("[TENANT] Failed to read response: %v", err)
		return
	}
	if closeErr != nil {
		t.Fatalf("[TENANT] Failed to close body: %v", closeErr)
		return
	}

	if res.StatusCode != 200 {
		t.Fatalf("[TENANT] Tenant not found (status %d): %s", res.StatusCode, string(body))
		return
	}

	bodyString := string(body)
	t.Logf("[TENANT] Tenant exists: %s", bodyString)
	require.Contains(t, bodyString, tenantId)
}

// VerifyExporterStatus checks exporter status and exporting state via the Zeebe actuator API.
// It logs the full exporter list and asserts that both exporters are ENABLED and exporting is not globally paused.
func VerifyExporterStatus(t *testing.T, cluster helpers.Cluster) {
	t.Helper()
	t.Logf("[EXPORTER STATUS] Checking exporter status for %s", cluster.ClusterName)

	endpoint, closeFn := NewServiceTunnelWithRetry(t, &cluster.KubectlNamespace, "camunda-zeebe-gateway", 0, 9600, 5, 15*time.Second)
	defer closeFn()

	// Check individual exporter status
	res, body := helpers.HttpRequest(t, "GET", fmt.Sprintf("http://%s/actuator/exporters", endpoint), nil)
	require.NotNil(t, res, "[EXPORTER STATUS] Failed to get exporter status - HTTP request returned nil")
	t.Logf("[EXPORTER STATUS] Exporters: %s", body)
	require.Equal(t, 200, res.StatusCode)
	require.Contains(t, body, "\"status\":\"ENABLED\"", "Expected at least one enabled exporter")
}

// CheckElasticsearchProcessInstanceCount queries ES directly for the number of process instance documents.
// This helps differentiate between exporter issues (records not in ES) and Operate importer issues (records in ES but not in Operate).
func CheckElasticsearchProcessInstanceCount(t *testing.T, cluster helpers.Cluster) {
	t.Helper()
	t.Logf("[ES DEBUG] Checking process instance count in ES for %s", cluster.ClusterName)

	esPassword := getElasticsearchPassword(t, &cluster.KubectlNamespace)

	output, err := k8s.RunKubectlAndGetOutputE(
		t,
		&cluster.KubectlNamespace,
		"exec",
		ElasticsearchPodName,
		"-c",
		"elasticsearch",
		"--",
		"curl",
		"-u", fmt.Sprintf("elastic:%s", esPassword),
		"-s",
		"localhost:9200/*process*/_count",
	)
	if err != nil {
		t.Logf("[ES DEBUG] Failed to query ES: %v", err)
		return
	}
	t.Logf("[ES DEBUG] ES process instance count: %s", output)
}

func CheckElasticsearchClusterHealth(t *testing.T, cluster helpers.Cluster) {
	t.Logf("[ELASTICSEARCH HEALTH] Checking cluster health for %s", cluster.ClusterName)

	esPassword := getElasticsearchPassword(t, &cluster.KubectlNamespace)

	var output string
	var err error

	// Retry up to 10 times with 15 second intervals to allow for cluster stabilization
	for i := 0; i < 10; i++ {
		output, err = k8s.RunKubectlAndGetOutputE(
			t,
			&cluster.KubectlNamespace,
			"exec",
			ElasticsearchPodName,
			"-c",
			"elasticsearch",
			"--",
			"curl",
			"-u", fmt.Sprintf("elastic:%s", esPassword),
			"-s",
			"localhost:9200/_cluster/health",
		)

		if err != nil {
			t.Logf("[ELASTICSEARCH HEALTH] Attempt %d/10: Error executing command: %v", i+1, err)
			if i < 9 {
				time.Sleep(15 * time.Second)
				continue
			}
			t.Fatalf("[ELASTICSEARCH HEALTH] Failed to get cluster health after 10 attempts: %v", err)
			return
		}

		// Parse the JSON response
		var health ElasticsearchClusterHealth
		if err := json.Unmarshal([]byte(output), &health); err != nil {
			t.Logf("[ELASTICSEARCH HEALTH] Attempt %d/10: Failed to parse response: %v", i+1, err)
			if i < 9 {
				time.Sleep(15 * time.Second)
				continue
			}
			t.Fatalf("[ELASTICSEARCH HEALTH] Failed to parse health response after 10 attempts: %v", err)
			return
		}

		t.Logf("[ELASTICSEARCH HEALTH] Attempt %d/10: Status = %s", i+1, health.Status)

		// Check if status is green (case-insensitive)
		if strings.ToLower(health.Status) == "green" {
			t.Logf("[ELASTICSEARCH HEALTH] Cluster health is green for %s", cluster.ClusterName)
			require.False(t, health.TimedOut, "Health check should not time out")
			return
		}

		if i < 9 {
			t.Logf("[ELASTICSEARCH HEALTH] Status is %s, waiting for green status...", health.Status)
			time.Sleep(15 * time.Second)
		}
	}

	t.Fatalf("[ELASTICSEARCH HEALTH] Cluster did not reach green status after 10 attempts. Last output: %s", output)
}

// WaitForGatewayAuthReady polls the Zeebe gateway /v2/topology endpoint with basic auth
// until it returns 200. This ensures that the CamundaExporter has finished creating ES
// indices (including camunda-user) so the gateway can authenticate requests.
func WaitForGatewayAuthReady(t *testing.T, kubectlOptions *k8s.KubectlOptions, maxRetries int, interval time.Duration) {
	t.Helper()

	endpoint, closeFn := NewServiceTunnelWithRetry(t, kubectlOptions, "camunda-zeebe-gateway", 0, 8080, 5, 15*time.Second)
	defer closeFn()

	url := fmt.Sprintf("http://%s/v2/topology", endpoint)

	for i := 0; i < maxRetries; i++ {
		client := &http.Client{Timeout: 10 * time.Second}
		req, err := http.NewRequest("GET", url, nil)
		if err != nil {
			t.Logf("[GATEWAY AUTH] request creation failed (attempt %d/%d): %v", i+1, maxRetries, err)
			time.Sleep(interval)
			continue
		}
		req.Header.Set("Authorization", basicAuthHeader())

		resp, err := client.Do(req)
		if err != nil {
			t.Logf("[GATEWAY AUTH] request failed (attempt %d/%d): %v", i+1, maxRetries, err)
			time.Sleep(interval)
			continue
		}
		resp.Body.Close()

		if resp.StatusCode == 200 {
			t.Logf("[GATEWAY AUTH] Zeebe gateway auth is ready (attempt %d/%d)", i+1, maxRetries)
			return
		}
		t.Logf("[GATEWAY AUTH] not ready yet (status %d, attempt %d/%d)", resp.StatusCode, i+1, maxRetries)
		time.Sleep(interval)
	}

	t.Fatalf("[GATEWAY AUTH] Zeebe gateway auth did not become ready after %d attempts", maxRetries)
}

// GetClusterTopology retrieves the current cluster topology information from the Zeebe gateway
func GetClusterTopology(t *testing.T, kubectlOptions *k8s.KubectlOptions) ClusterInfo {
	t.Helper()

	endpoint, closeFn := NewServiceTunnelWithRetry(t, kubectlOptions, "camunda-zeebe-gateway", 0, 8080, 5, 15*time.Second)
	defer closeFn()

	// Get topology from v2/topology endpoint
	code, body := http_helper.HTTPDoWithOptions(t, http_helper.HttpDoOptions{
		Method: "GET",
		Url:    fmt.Sprintf("http://%s/v2/topology", endpoint),
		Headers: map[string]string{
			"Authorization": basicAuthHeader(),
			"Accept":        "application/json",
		},
		TlsConfig: nil,
		Timeout:   30,
	})
	if code != 200 {
		t.Fatalf("[CLUSTER TOPOLOGY] Failed to get topology (status %d): %s", code, body)
		return ClusterInfo{}
	}
	require.NotEmpty(t, body)

	// Parse the topology response
	var clusterInfo ClusterInfo
	err := json.Unmarshal([]byte(body), &clusterInfo)
	require.NoError(t, err, "Failed to parse topology response")

	return clusterInfo
}

// WaitForZeebeStatefulSetReadyWithSelfHeal waits for every replica of the given
// StatefulSet to become Ready, deleting any broker pod that this wait has seen
// Running-but-not-Ready for at least stuckTimeout so the StatefulSet recreates it.
// The threshold is measured from when this wait first observed the pod
// Running-but-not-Ready, not from the pod/container start time.
//
// TODO(camunda/camunda#55038): remove once the broker no longer hangs
// permanently when a configured cross-region peer is briefly unresolvable.
// During failback the secondary region's clusterset DNS names are torn down and
// recreated, which can re-trigger the upstream startup hang on a broker that
// already passed the wait-clusterset-dns init gate: the management port 9600
// never opens, the pod stays 0/1 Running forever and never self-recovers, so a
// plain `kubectl rollout status` would simply time out. The init container only
// gates the *initial* startup and check-deployment-ready.sh (which carries the
// same self-heal) does not run in this Go failback path, so mirror that self-heal
// here to keep the failback deterministic.
func WaitForZeebeStatefulSetReadyWithSelfHeal(t *testing.T, kubectlOptions *k8s.KubectlOptions, statefulSetName string, overallTimeout, stuckTimeout, pollInterval time.Duration) {
	t.Helper()

	const maxSelfHealRestarts = 6
	deadline := time.Now().Add(overallTimeout)
	notReadySince := map[string]time.Time{}
	restarts := 0

	for {
		desired := strings.TrimSpace(runKubectlOrEmpty(t, kubectlOptions, "get", "statefulset", statefulSetName, "-o", "jsonpath={.spec.replicas}"))
		ready := strings.TrimSpace(runKubectlOrEmpty(t, kubectlOptions, "get", "statefulset", statefulSetName, "-o", "jsonpath={.status.readyReplicas}"))
		if desired != "" && desired != "0" && ready == desired {
			t.Logf("[SELF-HEAL WAIT] StatefulSet %s is fully ready (%s/%s) after %d self-heal restart(s)", statefulSetName, ready, desired, restarts)
			return
		}
		t.Logf("[SELF-HEAL WAIT] StatefulSet %s not ready yet (ready=%q desired=%q)", statefulSetName, ready, desired)

		now := time.Now()
		seen := map[string]bool{}
		for _, pod := range runningNotReadyPods(t, kubectlOptions, statefulSetName) {
			seen[pod] = true
			if _, tracked := notReadySince[pod]; !tracked {
				notReadySince[pod] = now
				continue
			}
			if now.Sub(notReadySince[pod]) >= stuckTimeout && restarts < maxSelfHealRestarts {
				t.Logf("[SELF-HEAL WAIT] Broker %s has been Running-but-not-Ready for at least %s since first observed; deleting it so the StatefulSet recreates it (camunda/camunda#55038)", pod, stuckTimeout)
				if err := k8s.RunKubectlE(t, kubectlOptions, "delete", "pod", pod, "--wait=false"); err != nil {
					t.Logf("[SELF-HEAL WAIT] failed to delete pod %s: %v", pod, err)
				} else {
					restarts++
					delete(notReadySince, pod)
				}
			}
		}
		// Stop tracking pods that recovered or were already recreated.
		for pod := range notReadySince {
			if !seen[pod] {
				delete(notReadySince, pod)
			}
		}

		if time.Now().After(deadline) {
			t.Fatalf("[SELF-HEAL WAIT] StatefulSet %s did not become ready within %s (self-heal restarts performed: %d)", statefulSetName, overallTimeout, restarts)
			return
		}
		time.Sleep(pollInterval)
	}
}

// runKubectlOrEmpty runs a read-only kubectl command and returns its trimmed
// output, or an empty string if the command fails (e.g. the resource does not
// exist yet). The error is logged rather than returned so the caller's retry loop
// stays simple while transient/auth/context failures remain visible in test output.
func runKubectlOrEmpty(t *testing.T, kubectlOptions *k8s.KubectlOptions, args ...string) string {
	t.Helper()
	out, err := k8s.RunKubectlAndGetOutputE(t, kubectlOptions, args...)
	if err != nil {
		t.Logf("[SELF-HEAL WAIT] kubectl %v failed (treating as empty): %v", args, err)
		return ""
	}
	return out
}

// runningNotReadyPods returns the names of pods belonging to the given
// StatefulSet (matched by the "<name>-" prefix) whose phase is Running but which
// have at least one container reporting not-Ready. Pods still in their init phase
// (the wait-clusterset-dns gate) report phase Pending and are intentionally
// excluded, so only brokers that started but failed to become Ready are healed.
func runningNotReadyPods(t *testing.T, kubectlOptions *k8s.KubectlOptions, statefulSetName string) []string {
	const jsonPath = "jsonpath={range .items[*]}{.metadata.name}{\"|\"}{.status.phase}{\"|\"}{range .status.containerStatuses[*]}{.ready}{\",\"}{end}{\";\"}{end}"
	out, err := k8s.RunKubectlAndGetOutputE(t, kubectlOptions, "get", "pods", "-o", jsonPath)
	if err != nil {
		t.Logf("[SELF-HEAL WAIT] failed to list pods: %v", err)
		return nil
	}

	var stuck []string
	for _, entry := range strings.Split(out, ";") {
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		fields := strings.Split(entry, "|")
		if len(fields) != 3 {
			continue
		}
		name, phase, readiness := fields[0], fields[1], fields[2]
		if !strings.HasPrefix(name, statefulSetName+"-") {
			continue
		}
		if phase == "Running" && strings.Contains(readiness, "false") {
			stuck = append(stuck, name)
		}
	}
	return stuck
}

// SelfHealStuckBrokers deletes any pod of the given StatefulSet that has been
// observed Running-but-not-Ready for at least stuckTimeout (e.g. a broker that hung
// on the cross-region clusterset-DNS race during a restart, camunda/camunda#55038,
// where the management port 9600 never opens), so the StatefulSet recreates it
// through the wait-clusterset-dns init gate and an in-flight cluster operation can
// finish. notReadySince tracks first-observed times across calls (keyed by
// namespace/pod), and restarts is bounded by maxRestarts. It mirrors the self-heal
// in check-deployment-ready.sh for code paths (broker scaling) that script does not
// cover. Returns the number of pods it deleted in this call.
func SelfHealStuckBrokers(t *testing.T, kubectlOptions *k8s.KubectlOptions, statefulSetName string, notReadySince map[string]time.Time, restarts *int, stuckTimeout time.Duration, maxRestarts int) int {
	t.Helper()

	now := time.Now()
	seen := map[string]bool{}
	stuckPod := ""
	for _, pod := range runningNotReadyPods(t, kubectlOptions, statefulSetName) {
		key := kubectlOptions.Namespace + "/" + pod
		seen[key] = true
		if _, tracked := notReadySince[key]; !tracked {
			notReadySince[key] = now
			continue
		}
		// Pick only the first broker eligible for restart and delete one at a time.
		// Restarting many brokers at once storms the cross-region clusterset DNS
		// (Submariner/Lighthouse must re-aggregate every changed pod IP), which
		// leaves peers NXDOMAIN ("resolved: null") and stalls cross-region
		// operations; healing incrementally avoids that.
		if stuckPod == "" && now.Sub(notReadySince[key]) >= stuckTimeout && *restarts < maxRestarts {
			stuckPod = pod
		}
	}

	deleted := 0
	if stuckPod != "" {
		t.Logf("[SELF-HEAL] Broker %s (ns %s) Running-but-not-Ready for >%s; deleting it so the StatefulSet recreates it (camunda/camunda#55038)", stuckPod, kubectlOptions.Namespace, stuckTimeout)
		if err := k8s.RunKubectlE(t, kubectlOptions, "delete", "pod", stuckPod, "--wait=false"); err != nil {
			t.Logf("[SELF-HEAL] failed to delete pod %s: %v", stuckPod, err)
		} else {
			*restarts++
			deleted = 1
			delete(notReadySince, kubectlOptions.Namespace+"/"+stuckPod)
		}
	}

	// Stop tracking pods (in this namespace) that recovered or were recreated.
	for key := range notReadySince {
		if strings.HasPrefix(key, kubectlOptions.Namespace+"/") && !seen[key] {
			delete(notReadySince, key)
		}
	}
	return deleted
}

// WaitForClusterTopologyConverged polls the Zeebe gateway /v2/topology until the
// cluster reports the expected number of brokers, evenly split across the two
// regions, with every partition healthy — or fails after maxRetries.
//
// During failback the primary StatefulSet can report all its pods Ready (so
// WaitForZeebeStatefulSetReadyWithSelfHeal returns) a few seconds before the
// cross-region cluster has re-formed to the full broker count. Steps that assume
// an already-converged cluster — CheckC8RunningProperly's single topology
// assertion, or the exporter-pause gateway call — are otherwise racy. Waiting for
// convergence here keeps the failback deterministic.
func WaitForClusterTopologyConverged(t *testing.T, kubectlOptions *k8s.KubectlOptions, expectedBrokers int, namespace0, namespace1 string, maxRetries int, interval time.Duration) {
	t.Helper()

	perRegion := expectedBrokers / 2
	for i := 0; i < maxRetries; i++ {
		converged, summary := fetchTopologyConvergence(t, kubectlOptions, expectedBrokers, perRegion, namespace0, namespace1)
		if converged {
			t.Logf("[CONVERGE WAIT] cluster converged: %s (attempt %d/%d)", summary, i+1, maxRetries)
			return
		}
		t.Logf("[CONVERGE WAIT] not converged yet: %s (attempt %d/%d)", summary, i+1, maxRetries)
		time.Sleep(interval)
	}
	t.Fatalf("[CONVERGE WAIT] cluster did not converge to %d healthy brokers (%d per region) after %d attempts", expectedBrokers, perRegion, maxRetries)
}

// fetchTopologyConvergence opens a fresh short-lived port-forward (re-selecting a
// currently-ready pod, so a broker restarting right after the redeploy cannot leave
// a dead tunnel that fails every subsequent poll) and reports whether /v2/topology
// shows the expected number of brokers, evenly split across regions, all healthy.
func fetchTopologyConvergence(t *testing.T, kubectlOptions *k8s.KubectlOptions, expectedBrokers, perRegion int, namespace0, namespace1 string) (bool, string) {
	t.Helper()

	endpoint, closeFn := NewServiceTunnelWithRetry(t, kubectlOptions, "camunda-zeebe-gateway", 0, 8080, 8, 15*time.Second)
	defer closeFn()

	client := &http.Client{Timeout: 10 * time.Second}
	req, err := http.NewRequest("GET", fmt.Sprintf("http://%s/v2/topology", endpoint), nil)
	if err != nil {
		return false, fmt.Sprintf("request creation failed: %v", err)
	}
	req.Header.Set("Authorization", basicAuthHeader())
	req.Header.Set("Accept", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return false, fmt.Sprintf("request failed: %v", err)
	}
	body, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	if resp.StatusCode != 200 {
		return false, fmt.Sprintf("status %d", resp.StatusCode)
	}

	var topology ClusterInfo
	if err := json.Unmarshal(body, &topology); err != nil {
		return false, fmt.Sprintf("parse error: %v", err)
	}

	primary, secondary, unhealthy := 0, 0, 0
	for _, b := range topology.Brokers {
		if strings.Contains(b.Host, namespace0) {
			primary++
		} else if strings.Contains(b.Host, namespace1) {
			secondary++
		}
		for _, p := range b.Partitions {
			if p.Health != "healthy" {
				unhealthy++
			}
		}
	}

	summary := fmt.Sprintf("brokers=%d (primary=%d, secondary=%d), unhealthy partitions=%d", len(topology.Brokers), primary, secondary, unhealthy)
	return len(topology.Brokers) == expectedBrokers && primary == perRegion && secondary == perRegion && unhealthy == 0, summary
}

// GatewayManagementRequest issues a request against the Zeebe gateway management
// API (port 9600), establishing a fresh, short-lived port-forward for the call.
// A long-lived tunnel breaks when the broker pod it targets restarts — which
// happens during partition redistribution on a broker-scaling change — so a
// per-call tunnel (which re-selects a currently-ready pod) plus a non-fatal error
// return lets callers retry instead of failing on a dropped connection.
func GatewayManagementRequest(t *testing.T, kubectlOptions *k8s.KubectlOptions, method, path string, payload []byte) (int, string, error) {
	t.Helper()

	endpoint, closeFn := NewServiceTunnelWithRetry(t, kubectlOptions, "camunda-zeebe-gateway", 0, 9600, 8, 15*time.Second)
	defer closeFn()

	var bodyReader io.Reader
	if payload != nil {
		bodyReader = bytes.NewReader(payload)
	}
	req, err := http.NewRequest(method, fmt.Sprintf("http://%s%s", endpoint, path), bodyReader)
	if err != nil {
		return 0, "", err
	}
	if payload != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return 0, "", err
	}
	defer resp.Body.Close()

	b, err := io.ReadAll(resp.Body)
	if err != nil {
		return resp.StatusCode, "", err
	}
	return resp.StatusCode, string(b), nil
}

// GatewayManagementMutate issues a mutating gateway management request (a broker
// scaling PATCH or an exporter enable/disable POST) and retries it on connection
// errors and transient 5xx responses. While partitions are being redistributed
// the gateway can briefly reject a mutating request with a 500 (the change is not
// applied), so a single-shot call is racy and can fail the whole failover/failback
// step on an intermittent server error. This retries with a backoff until the
// request is accepted (202), a definitive non-transient (<500) status is returned
// — which the caller then asserts on — or the retry budget is exhausted. It
// returns the last status, body and error observed.
func GatewayManagementMutate(t *testing.T, kubectlOptions *k8s.KubectlOptions, method, path string, payload []byte, maxRetries int, backoff time.Duration) (int, string, error) {
	t.Helper()

	var status int
	var body string
	var err error
	for i := 0; i < maxRetries; i++ {
		status, body, err = GatewayManagementRequest(t, kubectlOptions, method, path, payload)
		if err == nil && status < 500 {
			// 202 (accepted) or a definitive client-side status: stop retrying and
			// let the caller assert on the result.
			return status, body, nil
		}
		t.Logf("[GATEWAY] mutating %s %s not accepted yet (attempt %d/%d): status=%d err=%v; retrying in %s", method, path, i+1, maxRetries, status, err, backoff)
		time.Sleep(backoff)
	}
	return status, body, err
}
