---
schedules:
    - name: Mondays schedules 8.6
      branch: stable/8.6
      cron_every_day: Monday   # left null to run it everyday, otherwise separate days with a coma
      cron_every_hours: '22'   # left null to run it every hour, otherwise separate hours with a coma
      workflow_files:
          # AWS OpenShift ROSA HCP single region
          - .github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml

    - name: Everyday schedules 8.6
      branch: stable/8.6
      cron_every_day:
      cron_every_hours: '1'
      workflow_files:
          - .github/workflows/internal_global_links.yml
          - .github/workflows/aws_rosa_hcp_single_region_daily_cleanup.yml

    - name: Tuesday schedules 8.7
      branch: stable/8.7
      cron_every_day: Tuesday
      cron_every_hours: '22'
      workflow_files:
          # AWS OpenShift ROSA HCP single region
          - .github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
          # AWS OpenShift ROSA HCP dual region
          - .github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
          # AWS EKS Modules tests
          - .github/workflows/aws_modules_eks_rds_os_tests.yml
          - .github/workflows/aws_modules_eks_rds_os_create_destruct_tests.yml
          # AWS EKS Single Region
          - .github/workflows/aws_kubernetes_eks_single_region_tests.yml
          - .github/workflows/aws_common_procedure_s3_bucket.yml

    - name: Everyday schedules 8.7
      branch: stable/8.7
      cron_every_day:
      cron_every_hours: '1'
      workflow_files:
          - .github/workflows/internal_global_links.yml
          - .github/workflows/aws_rosa_hcp_single_region_daily_cleanup.yml
          - .github/workflows/aws_rosa_hcp_dual_region_daily_cleanup.yml
          - .github/workflows/aws_modules_eks_rds_os_daily_cleanup.yml
          - .github/workflows/aws_eks_single_region_daily_cleanup.yml

    - name: Wednesday schedules 8.8
      branch: stable/8.8
      cron_every_day: Wednesday
      cron_every_hours: '22'
      workflow_files:
          # AWS OpenShift ROSA HCP single region
          - .github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml
          # AWS OpenShift ROSA HCP dual region
          - .github/workflows/aws_openshift_rosa_hcp_dual_region_tests.yml
          # AWS EKS Modules tests
          - .github/workflows/aws_modules_eks_rds_os_tests.yml
          - .github/workflows/aws_modules_eks_rds_os_create_destruct_tests.yml
          # AWS EKS Single Region
          - .github/workflows/aws_kubernetes_eks_single_region_tests.yml
          - .github/workflows/aws_common_procedure_s3_bucket.yml
          # AWS EC2 Single Region
          - .github/workflows/aws_compute_ec2_single_region_tests.yml
          # Azure AKS Single Region
          - .github/workflows/azure_kubernetes_aks_single_region_tests.yml
          # Generic Kubernetes Operator Based
          - .github/workflows/generic_kubernetes_operator_based_test.yml
          # Local Kubernetes Kind Single Region
          - .github/workflows/local_kubernetes_kind_single_region_tests.yml

    - name: Everyday schedules 8.8
      branch: stable/8.8
      cron_every_day:
      cron_every_hours: '1'
      workflow_files:
          - .github/workflows/internal_global_links.yml
          - .github/workflows/aws_rosa_hcp_single_region_daily_cleanup.yml
          - .github/workflows/aws_rosa_hcp_dual_region_daily_cleanup.yml
          - .github/workflows/aws_modules_eks_rds_os_daily_cleanup.yml
          - .github/workflows/aws_eks_single_region_daily_cleanup.yml
          - .github/workflows/aws_compute_ec2_single_region_daily_cleanup.yml
          - .github/workflows/azure_aks_single_region_daily_cleanup.yml
