---
schedules:
    - name: Mondays schedules 8.6
      branch: feature/integrate-tests-rosa
      cron_every_day: Monday   # left null to run it everyday, otherwise separate days with a coma
      cron_every_hours: '1' # left null to run it every hour, otherwise separate hours with a coma
      workflow_files:
          # AWS OpenShift ROSA HCP single region
          - .github/workflows/aws_openshift_rosa_hcp_single_region_daily_cleanup.yml
          - .github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml

          # AWS EC2
          - .github/workflows/aws_ec2_tests.yml
