---
schedules:
    - name: Mondays schedules 8.6
      branch: feature/integrate-tests-rosa
      cron: 0 1 * * 1 # every Mondays @ 1AM
      workflow_files:
          # AWS OpenShift ROSA HCP single region
          - .github/workflows/aws_openshift_rosa_hcp_single_region_daily_cleanup.yml
          - .github/workflows/aws_openshift_rosa_hcp_single_region_tests.yml

          # AWS EC2
          - .github/workflows/aws_ec2_tests.yml
