---
name: Internal Multi-Region Tests
description: Run tests across multiple regions
inputs:
    cluster-0-namespace:
        description: Camunda namespace for Cluster 0
        required: true
        default: camunda-platform
    cluster-1-namespace:
        description: Camunda namespace for Cluster 1
        required: true
        default: camunda-platform
    helm-version:
        description: Helm version to test
        required: true
    cluster-name:
        description: Value used for naming some things but not actively used to decide on context
        required: false
        default: dual-region-cluster
    backup-name:
        description: Name of the backup that should be created, important in shared s3 buckets
        required: false
    default-values-yaml:
        description: Path to default values yaml file
        required: false
        default: ./multi-region-tests/test/values.yaml
    region-0-values-yaml:
        description: Path to region 0 values yaml file
        required: false
        default: ./multi-region-tests/test/values-region-0.yaml
    region-1-values-yaml:
        description: Path to region 1 values yaml file
        required: false
        default: ./multi-region-tests/test/values-region-1.yaml
    extra-values-yaml:
        description: Comma separated string of extra values yaml files to be applied
        required: false
        default: ''
runs:
    using: composite
    steps:
        - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
          with:
              repository: camunda/c8-multi-region
              ref: infraex-559-SNAPSHOT
              path: multi-region-tests
        - name: Split up Kubeconfig
          shell: bash
          run: |
              set -euo pipefail
              # there's a 3rd context in there that skews with the order
              yq eval '
              {
                "apiVersion": .apiVersion,
                "kind": .kind,
                "preferences": .preferences,
                "clusters": [ .clusters[0] ],
                "contexts": [ .contexts[1] ],
                "current-context": .contexts[1].name,
                "users": [ .users[0] ]
              }
              ' $HOME/.kube/config > ./multi-region-tests/test/kubeconfig-london

              yq eval '
              {
                "apiVersion": .apiVersion,
                "kind": .kind,
                "preferences": .preferences,
                "clusters": [ .clusters[1] ],
                "contexts": [ .contexts[2] ],
                "current-context": .contexts[2].name,
                "users": [ .users[1] ]
              }
              ' $HOME/.kube/config > ./multi-region-tests/test/kubeconfig-paris
        - name: Set Up Environment Variables
          shell: bash
          run: |
              set -euo pipefail

              if [[ inputs.helm-version =~ snapshot ]]; then
                {
                  echo "HELM_CHART_NAME=oci://ghcr.io/camunda/helm/camunda-platform"
                  echo "GLOBAL_IMAGE_TAG=SNAPSHOT"
                } >> "$GITHUB_ENV"
              fi

              {
                echo "CLUSTER_0_NAMESPACE=${{ inputs.cluster-0-namespace }}"
                echo "CLUSTER_1_NAMESPACE=${{ inputs.cluster-1-namespace }}"
                echo "HELM_CHART_VERSION=${{ inputs.helm-version }}"
                echo "CLUSTER_NAME=${{ inputs.cluster-name }}"
                echo "BACKUP_NAME${{ inputs.backup-name }}"
                echo "DEFAULT_VALUES_YAML=${{ inputs.default-values-yaml }}"
                echo "REGION0_VALUES_YAML=${{ inputs.region-0-values-yaml }}"
                echo "REGION1_VALUES_YAML=${{ inputs.region-1-values-yaml }}"
                echo "EXTRA_VALUES_YAML=${{ inputs.extra-values-yaml }}"
              } >> "$GITHUB_ENV"
        - name: Set start timestamp for Failover
          shell: bash
          id: failover-start
          run: |
              set -euo pipefail

              printf 'timestamp=%(%s)T\n' >> "$GITHUB_OUTPUT"
        - name: Failover ${{ inputs.helm-version }}
          shell: bash
          working-directory: ./multi-region-tests/test
          run: |
              set -euo pipefail

              go test --count=1 -v -timeout 20m -run TestAWSDualRegFailover_8_6_plus
        - name: Calculate Failover duration
          shell: bash
          run: |
              set -euo pipefail

              printf -v now '%(%s)T'
              duration=$((now - ${{ steps.failover-start.outputs.timestamp }}))
              echo $duration
              if [ "$duration" -gt "900" ]; then
              echo "::error ::Failover of ${{ inputs.helm-version }} is taking longer than 15 minutes"
              fi
        - name: Set start timestamp for Failback
          shell: bash
          id: failback-start
          run: |
              set -euo pipefail

              printf 'timestamp=%(%s)T\n' >> "$GITHUB_OUTPUT"
        - name: Failback - ${{ inputs.helm-version }}
          shell: bash
          working-directory: ./multi-region-tests/test
          run: |
              set -euo pipefail

              go test --count=1 -v -timeout 45m -run TestAWSDualRegFailback_8_6_plus
        - name: Calculate Failback duration
          shell: bash
          run: |
              set -euo pipefail

              printf -v now '%(%s)T'
              duration=$((now - ${{ steps.failback-start.outputs.timestamp }}))
              echo $duration
              if [ "$duration" -gt "1500" ]; then
              echo "::error ::Failback of ${{ inputs.helm-version }} is taking longer than 25 minutes"
              fi
    # - name: Test multi-tenancy - ${{ inputs.helm-version }}
    #   shell: bash
    #   if: ${{ fromJSON(env.MAJOR_VERSION) >= 13 }}
    #   working-directory: ./multi-region-tests/test
    #   run: |
    #       go test --count=1 -v -timeout 20m -run TestMultiTenancyDualReg
        - name: Debug Step
          shell: bash
          working-directory: ./multi-region-tests/test
          if: failure()
          run: |
              set -euo pipefail

              go test --count=1 -v -timeout 4m -run TestDebugStep
        - name: Upload Pod Logs
          if: failure()
          uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
          with:
              name: pod-logs-${{ inputs.helm-version }}
              retention-days: 7
              path: ./multi-region-tests/test/*.log
