---
name: Deploy RDS Aurora Cluster

description: |
    This GitHub Action automates the deployment of an RDS Aurora cluster using Terraform.
    This action will also install Terraform and awscli. It will output the Aurora cluster endpoint.

inputs:
    aws-region:
        description: AWS region where the cluster will be deployed
        required: true

    cluster-name:
        description: Name of the RDS Aurora cluster to deploy
        required: true

    username:
        description: Username for the PostgreSQL admin user
        required: true

    password:
        description: Password for the PostgreSQL admin user
        required: true

    vpc-id:
        description: VPC ID to create the cluster in
        required: true

    subnet-ids:
        description: List of subnet IDs to create the cluster in
        required: true

    cidr-blocks:
        description: CIDR blocks to allow access from and to
        required: true

    availability-zones:
        description: Array of availability zones to use for the Aurora cluster
        required: true

    additional-terraform-vars:
        description: JSON object containing additional Terraform variables
        required: false
        default: '{}'

    s3-backend-bucket:
        description: Name of the S3 bucket to store Terraform state
        required: true

    s3-bucket-region:
        description: Region of the bucket containing the resources states
        required: false

    s3-bucket-key-prefix:
        description: Key prefix of the bucket containing the resources states. It must contain a / at the end e.g 'my-prefix/'.
        default: ''

    tf-modules-revision:
        description: Git revision of the tf modules to use
        default: main

    tf-modules-path:
        description: Path where the tf Aurora modules will be cloned
        default: ./.action-tf-modules/aurora/

    # inherited from https://github.com/hashicorp/setup-terraform/blob/main/action.yml
    tf-cli-config-credentials-hostname:
        description: |
            The hostname of a HCP Terraform/Terraform Enterprise instance to place within the credentials block
            of the Terraform CLI configuration file. Defaults to `app.terraform.io`.
        default: app.terraform.io

    tf-cli-config-credentials-token:
        description: |
            The API token for a HCP Terraform/Terraform Enterprise instance to place
            within the credentials block of the Terraform CLI configuration file.
        required: false

    tf-terraform-version:
        description: The version of Terraform CLI to install. Defaults to `latest`.
        default: latest

    tf-terraform-wrapper:
        description: |
            Whether or not to install a wrapper to wrap subsequent calls of the `terraform` binary
            and expose its STDOUT, STDERR, and exit code
            as outputs named `stdout`, `stderr`, and `exitcode` respectively. Defaults to `true`.
        default: 'true'

    awscli-version:
        description: Version of the aws cli to use
        # renovate: datasource=github-releases depName=aws/aws-cli
        default: 2.15.52

    tags:
        description: Tags to apply to the cluster and related resources, in JSON format
        default: '{}'

outputs:
    aurora-endpoint:
        description: The endpoint of the deployed Aurora cluster
        value: ${{ steps.terraform_outputs.outputs.aurora_endpoint }}

    terraform-state-url:
        description: URL of the Terraform state file in the S3 bucket
        value: ${{ steps.utility.outputs.terraform-state-url }}

    all-terraform-outputs:
        description: All outputs from Terraform as a JSON blob
        value: ${{ steps.terraform_outputs.outputs.all_terraform_outputs }}

runs:
    using: composite
    steps:
        - name: Use Utility Actions
          id: utility
          # see https://github.com/orgs/community/discussions/41927 it's not possible to optimize this yet
          # steps.uses  cannot access the github context.
          uses: camunda/camunda-deployment-references/.github/actions/aws-utility-action@main
          with:
              awscli-version: ${{ inputs.awscli-version }}
              terraform-version: ${{ inputs.terraform-version }}

              aws-region: ${{ inputs.aws-region }}

              s3-backend-bucket: ${{ inputs.s3-backend-bucket }}
              s3-bucket-region: ${{ inputs.s3-bucket-region }}

              tf-state-key: ${{ inputs.s3-bucket-key-prefix }}tfstate-${{ inputs.cluster-name }}/${{ inputs.cluster-name }}.tfstate

              tf-cli-config-credentials-hostname: ${{ inputs.tf-cli-config-credentials-hostname }}
              tf-cli-config-credentials-token: ${{ inputs.tf-cli-config-credentials-token }}
              tf-terraform-wrapper: ${{ inputs.tf-terraform-wrapper }}

        - name: Checkout Repository Aurora modules
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
          with:
              repository: camunda/camunda-deployment-references
              ref: ${{ inputs.tf-modules-revision }}
              path: ${{ inputs.tf-modules-path }}
              fetch-depth: 0

        - name: Set working directory
          shell: bash
          run: echo "TF_MODULE_DIR=${{ inputs.tf-modules-path }}/aws/modules/aurora" >> "$GITHUB_ENV"

        - name: Terraform Init
          shell: bash
          id: init
          working-directory: ${{ env.TF_MODULE_DIR }}
          run: |
              set -euo pipefail

              cp ../fixtures/backend.tf ./
              terraform version
              terraform init -backend-config="bucket=${{ steps.utility.outputs.TFSTATE_BUCKET }}" -backend-config="key=${{ steps.utility.outputs.TFSTATE_KEY }}" \
                -backend-config="region=${{ steps.utility.outputs.TFSTATE_REGION }}"
              terraform validate -no-color

        - name: Sanitize Tags
          id: sanitize-tags
          uses: ./.github/actions/internal-sanitize-tags
          with:
              raw-tags: ${{ inputs.tags }}

        - name: Generate tfvars file
          id: generate-tfvars
          shell: bash
          working-directory: ${{ env.TF_MODULE_DIR }}
          run: |
              set -euo pipefail

              # protect sensitive values
              echo "::add-mask::${{ inputs.password }}"

              cat > terraform.tfvars <<EOF
              default_tags = ${{ steps.sanitize-tags.outputs.sanitized_tags }}
              cluster_name = "${{ inputs.cluster-name }}"
              username     = "${{ inputs.username }}"
              password     = "${{ inputs.password }}"
              availability_zones = ${{ inputs.availability-zones }}
              vpc_id       = "${{ inputs.vpc-id }}"
              subnet_ids   = ${{ inputs.subnet-ids }}
              cidr_blocks  = ${{ inputs.cidr-blocks }}
              EOF

        - name: Terraform Plan
          shell: bash
          id: plan
          working-directory: ${{ env.TF_MODULE_DIR }}
          run: |
              set -euo pipefail

              echo '${{ inputs.additional-terraform-vars }}' > /tmp/var.tfvars.json
              terraform plan -no-color -out aurora.plan \
                -var-file=/tmp/var.tfvars.json \
                -var-file=terraform.tfvars

        - name: Terraform Apply
          shell: bash
          id: apply
          working-directory: ${{ env.TF_MODULE_DIR }}
          run: |
              set -euo pipefail

              terraform apply -no-color aurora.plan

        - name: Export Terraform Outputs
          shell: bash
          id: terraform_outputs
          working-directory: ${{ env.TF_MODULE_DIR }}
          run: |
              source "${{ github.workspace }}/.github/scripts/gha-functions.sh"
              export_terraform_outputs

        - name: Terraform Drift Detection
          uses: ./.github/actions/internal-terraform-drift-detect
          id: drift-detect
          with:
              working-directory: ${{ env.TF_MODULE_DIR }}
              plan-extra-args: |
                  -var-file=/tmp/var.tfvars.json \
                  -var-file=terraform.tfvars
