#!/bin/bash

set -euo pipefail

# This script applies the import secret generated by ACM to the managed clusters
# to install the klusterlet agent.
#
# The ManagedCluster-Import-Controller generates a secret named ${CLUSTER_NAME}-import
# that contains the import.yaml manifest which must be applied to the managed cluster.
#
# Reference:
# https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.3/html/clusters/importing-a-target-managed-cluster-to-the-hub-cluster#importing-a-managed-cluster-with-the-cli

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Applying import secrets to managed clusters"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Function to wait for import secret to be generated
wait_for_import_secret() {
    local cluster_name=$1
    local max_attempts=60
    local attempt=0

    echo "⏳ Waiting for import secret '${cluster_name}-import' to be generated..."

    while [ $attempt -lt $max_attempts ]; do
        if oc --context "$CLUSTER_1_NAME" get secret "${cluster_name}-import" -n "${cluster_name}" &>/dev/null; then
            echo "✅ Import secret '${cluster_name}-import' found"
            return 0
        fi

        attempt=$((attempt + 1))
        echo "   Attempt ${attempt}/${max_attempts}: waiting for secret..."
        sleep 5
    done

    echo "❌ ERROR: Import secret '${cluster_name}-import' was not generated after ${max_attempts} attempts"
    return 1
}

# Function to extract and apply import manifest
apply_import_manifest() {
    local cluster_name=$1
    local target_context=$2

    echo ""
    echo "📦 Processing cluster: ${cluster_name}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Wait for the import secret to be generated
    if ! wait_for_import_secret "${cluster_name}"; then
        return 1
    fi

    echo "📄 Extracting import manifest from secret..."
    local import_manifest
    import_manifest=$(oc --context "$CLUSTER_1_NAME" get secret "${cluster_name}-import" \
        -n "${cluster_name}" \
        -o jsonpath='{.data.import\.yaml}' | base64 -d)

    if [ -z "$import_manifest" ]; then
        echo "❌ ERROR: Failed to extract import manifest from secret"
        return 1
    fi

    echo "✅ Import manifest extracted successfully"

    # Apply the import manifest to the target cluster
    echo "🚀 Applying import manifest to cluster '${cluster_name}' (context: ${target_context})..."
    if echo "$import_manifest" | oc --context "${target_context}" apply -f -; then
        echo "✅ Import manifest applied successfully to ${cluster_name}"
    else
        echo "❌ ERROR: Failed to apply import manifest to ${cluster_name}"
        return 1
    fi

    # Wait for klusterlet to be ready
    echo "⏳ Waiting for klusterlet to be ready..."
    local max_wait=180
    local elapsed=0

    while [ $elapsed -lt $max_wait ]; do
        if oc --context "${target_context}" get klusterlet &>/dev/null; then
            local klusterlet_status
            klusterlet_status=$(oc --context "${target_context}" get klusterlet -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "")

            if [ "$klusterlet_status" = "True" ]; then
                echo "✅ Klusterlet is ready on ${cluster_name}"
                return 0
            fi
        fi

        elapsed=$((elapsed + 5))
        echo "   Waiting for klusterlet... (${elapsed}s/${max_wait}s)"
        sleep 5
    done

    echo "⚠️  WARNING: Klusterlet readiness timeout, but continuing (it may still be initializing)"
    return 0
}

# Apply import manifest for local-cluster (cluster 1)
echo ""
echo "🔹 Cluster 1: local-cluster"
if ! apply_import_manifest "local-cluster" "$CLUSTER_1_NAME"; then
    echo "❌ Failed to apply import manifest for local-cluster"
    exit 1
fi

# Apply import manifest for cluster 2
echo ""
echo "🔹 Cluster 2: ${CLUSTER_2_NAME}"
if ! apply_import_manifest "$CLUSTER_2_NAME" "$CLUSTER_2_NAME"; then
    echo "❌ Failed to apply import manifest for ${CLUSTER_2_NAME}"
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Import manifests applied successfully to all clusters"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Checking ManagedCluster status..."
oc --context "$CLUSTER_1_NAME" get managedclusters
