#!/bin/bash

# Apply the import secrets generated by ACM to the managed clusters.
# The import secret contains the manifest to install the klusterlet agent.

echo "Applying import secret for local-cluster..."
while true; do
    if oc --context "$CLUSTER_1_NAME" get secret local-cluster-import -n local-cluster &>/dev/null; then
        echo "Import secret found, extracting and applying manifest..."
        oc --context "$CLUSTER_1_NAME" get secret local-cluster-import \
            -n local-cluster \
            -o jsonpath='{.data.import\.yaml}' | base64 -d | \
            oc --context "$CLUSTER_1_NAME" apply -f -
        break
    fi
    echo "Waiting for import secret..."
    sleep 5
done

echo "Applying import secret for $CLUSTER_2_NAME..."
while true; do
    if oc --context "$CLUSTER_1_NAME" get secret "${CLUSTER_2_NAME}-import" -n "$CLUSTER_2_NAME" &>/dev/null; then
        echo "Import secret found, extracting and applying manifest..."
        oc --context "$CLUSTER_1_NAME" get secret "${CLUSTER_2_NAME}-import" \
            -n "$CLUSTER_2_NAME" \
            -o jsonpath='{.data.import\.yaml}' | base64 -d | \
            oc --context "$CLUSTER_2_NAME" apply -f -
        break
    fi
    echo "Waiting for import secret..."
    sleep 5
done

echo "Import secrets applied successfully"
oc --context "$CLUSTER_1_NAME" get managedclusters
