---
matrix:
    distro:
        - name: OpenShift 4.19
          schedule_only: false
          # renovate: datasource=custom.rosa-camunda depName=red-hat-openshift versioning=regex:^4(\.(?<minor>\d+))?(\.(?<patch>\d+))?$
          version: 4.20.3

    scenario:
        - name: rosa-hcp-dual-region
          # Auth provider: 'keycloak' (embedded) or 'oidc' (external like Cognito, EntraID)
          # TODO: Add 'oidc' support with AWS Cognito
          auth_provider: keycloak
