---
matrix:
    distro:
        - name: OpenShift 4.18
          type: openshift
          schedule_only: false
          # renovate: datasource=custom.rosa-camunda depName=red-hat-openshift versioning=regex:^4(\.(?<minor>\d+))?(\.(?<patch>\d+))?$
          version: 4.18.4
          platform: rosa

    scenario:
        - name: Chart Setup
          desc: Setup chart in production-like setup with Ingress and TLS.
          flow: install
