---
matrix:
    distro:
        - name: OpenShift 4.18
          type: openshift
          schedule_only: false
          # renovate: datasource=custom.rosa-camunda depName=red-hat-openshift versioning=regex:^4(\.(?<minor>\d+))?(\.(?<patch>\d+))?$
          version: 4.18.5
          platform: rosa

    scenario:
        - name: rosa-hcp-dual-region
