---
global:
    elasticsearch:
        enabled: true # use the embbeded elasticsearch

identityKeycloak:
    postgresql:
        enabled: true # use the embbeded database

        # TODO: [BUG] 8.6 only remove when https://github.com/camunda/camunda-platform-helm/pull/3018 is released and chart is set to 11.2.2
        # context https://github.com/camunda/camunda-platform-helm/pull/2944
        auth:
            existingSecret: ''

    auth:
        existingSecret: identity-secret-for-components

connectors:
    # TODO: investigate why connectors are not working in 8.7
    enabled: true

console:
    enabled: false # by default, console is not enabled

webModeler:
    enabled: false # by default, webModeler is not enabled

    restapi:
        mail:
            existingSecret: identity-secret-for-components # reference the smtp password
            fromAddress: changeme@example.com   # change this required value
postgresql:
    # Will deploy a postgresql datbase for webModeler.
    # If you enable webModeler, you either need to turn it true or use an external database
    enabled: false
