---
global:
    elasticsearch:
        enabled: true # use the embbeded elasticsearch

identity:
    image:
        tag: 8.8-SNAPSHOT # TODO: remove!

orchestration:
    image:
        tag: 8.8-SNAPSHOT # TODO: remove!

optimize:
    image:
        tag: 8.8-SNAPSHOT # TODO: remove!

connectors:
    enabled: true
    image:
        tag: 8.8-SNAPSHOT # TODO: remove!

console:
    enabled: false # by default, console is not enabled
    image:
        tag: 8.8-SNAPSHOT # TODO: remove!

webModeler:
    enabled: false # by default, webModeler is not enabled
    image:
        tag: 8.8-SNAPSHOT # TODO: remove!

    restapi:
        mail:
            secret:
                existingSecret: identity-secret-for-components # reference the smtp password
                existingSecretKey: smtp-password
            fromAddress: changeme@example.com   # change this required value

webModelerPostgresql:
    # Will deploy a postgresql database for webModeler.
    # If you enable webModeler, you either need to turn it true or use an external database
    enabled: false
    auth:
        existingSecret: identity-secret-for-components
        secretKeys:
            adminPasswordKey: identity-webmodeler-postgres-admin-password
            userPasswordKey: identity-webmodeler-postgres-user-password
