---
# OpenShift Base Configuration for Camunda Platform
#
# This is the base values file for Camunda components.
# Infrastructure services (Elasticsearch, PostgreSQL, Keycloak) are managed via
# Kubernetes operators and configured through separate overlay files:
#
# Operator overlays (always applied):
# - Elasticsearch: generic/kubernetes/operator-based/elasticsearch/camunda-elastic-values.yml
# - PostgreSQL Identity: generic/kubernetes/operator-based/postgresql/camunda-identity-values.yml
# - PostgreSQL WebModeler: generic/kubernetes/operator-based/postgresql/camunda-webmodeler-values.yml
#
# Auth provider overlays (choose one):
# - Keycloak Operator: generic/kubernetes/operator-based/keycloak/camunda-keycloak-*-values.yml
# - OIDC: generic/kubernetes/single-region/helm-values/values-oidc.yml + values-oidc-*.yml

global:
    security:
        authentication:
            method: oidc

    identity:
        enabled: true
        auth:
            enabled: true

orchestration:
    contextPath: /

    security:
        initialization:
            defaultRoles:
                admin:
                    users:
                        - admin

optimize:
    enabled: true

connectors:
    enabled: true

console:
    enabled: false # by default, console is not enabled

identity:
    enabled: true

    firstUser:
        enabled: true
        username: admin
        email: admin@camunda.local
        firstName: Admin
        lastName: User
        secret:
            existingSecret: identity-secret-for-components
            existingSecretKey: identity-first-user-password

webModeler:
    enabled: false # by default, webModeler is not enabled

    restapi:
        mail:
            secret:
                existingSecret: webmodeler-secret
                existingSecretKey: smtp-password
            fromAddress: changeme@example.com   # change this required value

# WebModeler PostgreSQL is managed by the CNPG operator.
# See generic/kubernetes/operator-based/postgresql/ for the CNPG cluster definitions
# and camunda-webmodeler-values.yml for the corresponding Helm overlay.
webModelerPostgresql:
    enabled: false
