---
matrix:
    distro:
        - name: x86_64
          schedule_only: false
          # TODO: Enable again after everything is implemented
          # - name: arm64
          #   schedule_only: false

    scenario:
        - name: ec2-single-region

    declination:
        - name: no-domain
          desc: Setup in production-like setup without Ingress and TLS.
