---
global:
    elasticsearch:
        enabled: true # use the embbeded elasticsearch

    secrets:
        name: identity-secret-for-components

identity:
    firstUser:
        existingSecret: identity-secret-for-components

identityKeycloak:
    postgresql:
        enabled: true # use the embbeded database
        auth:
            existingSecret: identity-secret-for-components
    auth:
        existingSecret: identity-secret-for-components

console:
    enabled: false # by default, console is not enabled

webModeler:
    enabled: false # by default, webModeler is not enabled

    restapi:
        mail:
            fromAddress: changeme@example.com   # change this required value
