---
global:
    elasticsearch:
        enabled: true # use the embbeded elasticsearch

identityKeycloak:
    postgresql:
        enabled: true # use the embbeded database
    auth:
        existingSecret: identity-secret-for-components

console:
    enabled: false # by default, console is not enabled

webModeler:
    enabled: false # by default, webModeler is not enabled

    restapi:
        mail:
            existingSecret: identity-secret-for-components # reference the smtp password
            fromAddress: changeme@example.com   # change this required value


core:
    ##### Gateway Identity auth mode
    env:
        - name: ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_MODE
          value: identity

        - name: ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL
          value: http://camunda-keycloak:80/auth/realms/camunda-platform

        - name: ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_AUDIENCE
          value: core-api

        - name: ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_TYPE
          value: keycloak
