---
name: Configure Wildcard Certificate Usage
description: |
    Determines whether to use wildcard certificates or Let's Encrypt based on PR context.
    For Renovate PRs, automatically detects if cert-manager is modified.

inputs:
    manual-wildcard-cert:
        description: Manual override to use wildcard certificate (takes precedence)
        required: false
        default: ''
    is-renovate-pr:
        description: Whether this is a Renovate bot PR
        required: true
    is-schedule:
        description: Whether this is a scheduled run
        required: true
    base-ref:
        description: Base branch reference for diff comparison
        required: false
        default: main

outputs:
    use-wildcard-cert:
        description: Whether to use wildcard certificate (true/false)
        value: ${{ steps.configure.outputs.USE_WILDCARD_CERT }}
    has-cert-manager-changes:
        description: Whether the PR contains cert-manager changes (only set for Renovate PRs)
        value: ${{ steps.check_cert_manager_changes.outputs.HAS_CERT_MANAGER_CHANGES }}

runs:
    using: composite
    steps:
        - name: Check if PR contains cert-manager changes (Renovate only)
          if: github.event_name == 'pull_request' && inputs.is-renovate-pr == 'true'
          id: check_cert_manager_changes
          shell: bash
          run: |
              set -euo pipefail

              echo "🔍 Checking for cert-manager changes in Renovate PR..."

              # Check if PR contains changes to cert-manager
              CHANGED_FILES=$(git diff --name-only origin/${{ inputs.base-ref }}...HEAD || echo "")

              if echo "$CHANGED_FILES" | grep -qE "cert-manager"; then
                  echo "HAS_CERT_MANAGER_CHANGES=true" | tee -a "$GITHUB_OUTPUT"
                  echo "✅ Detected cert-manager changes in PR, will use Let's Encrypt certificates"
              else
                  echo "HAS_CERT_MANAGER_CHANGES=false" | tee -a "$GITHUB_OUTPUT"
                  echo "ℹ️  No cert-manager changes detected, will use wildcard certificate"
              fi

        - name: Configure wildcard certificate usage
          id: configure
          shell: bash
          run: |
              set -euo pipefail

              echo "🔧 Determining certificate configuration strategy..."

              # Logic: Manual override takes precedence over everything
              # - If manual-wildcard-cert is set (not empty) -> use its value directly
              # - Then use Let's Encrypt ONLY for Renovate PRs on main with cert-manager changes
              # - All other cases use wildcard certificate (default)

              if [[ -n "${{ inputs.manual-wildcard-cert }}" ]]; then
                  USE_WILDCARD="${{ inputs.manual-wildcard-cert }}"
                  echo "📋 Manual override: USE_WILDCARD_CERT=$USE_WILDCARD"
              elif [[ "${{ github.event_name }}" == "pull_request" && \
                    "${{ inputs.is-renovate-pr }}" == "true" && \
                    "${{ inputs.base-ref }}" == "main" && \
                    "${{ steps.check_cert_manager_changes.outputs.HAS_CERT_MANAGER_CHANGES }}" == "true" ]]; then
                  USE_WILDCARD="false"
                  echo "🎫 Renovate PR targeting main with cert-manager changes: Using Let's Encrypt to test cert-manager"
              else
                  USE_WILDCARD="true"
                  echo "🎫 Using wildcard certificate (default)"
              fi

              echo "USE_WILDCARD_CERT=$USE_WILDCARD" | tee -a "$GITHUB_OUTPUT"
              echo ""
              echo "📊 Summary:"
              echo "  - Manual override: ${{ inputs.manual-wildcard-cert }}"
              echo "  - Is Renovate PR: ${{ inputs.is-renovate-pr }}"
              echo "  - Target branch: ${{ inputs.base-ref }}"
              echo "  - Is Schedule: ${{ inputs.is-schedule }}"
              echo "  - Has cert-manager Changes: ${{ steps.check_cert_manager_changes.outputs.HAS_CERT_MANAGER_CHANGES || 'N/A' }}"
              echo "  - Final Decision: USE_WILDCARD_CERT=$USE_WILDCARD"
