---
name: Tests - Integration - AWS EC2
on:
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ !contains('renovate[bot]', github.actor) }}
env:
    IS_SCHEDULE: ${{ contains(github.ref, 'refs/heads/schedules/') || github.event_name == 'schedule' && 'true' || 'false' }}
    AWS_PROFILE: infex
    AWS_REGION: eu-west-2
    S3_BACKEND_BUCKET: tf-state-multi-reg
    S3_BUCKET_REGION: eu-central-1
    SNAPSHOT_PREVIOUS_VERSION: 8.7.0-alpha3-rc4
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                camunda:
                    - 8.6.10
                    - 8.7.0-SNAPSHOT
                architecture:
                    - x86_64
                    - arm64
                isPR:
                    - ${{ github.event_name == 'pull_request' && !contains(github.head_ref, 'SNAPSHOT') }}
                previous_camunda:
                    - 8.6.2
                exclude:
                    - camunda: 8.7.0-SNAPSHOT
                      isPR: true
        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
            - name: Install asdf tools with cache
              uses: camunda/infraex-common-config/./.github/actions/asdf-install-tooling@6dc218bf7ee3812a4b6b13c305bce60d5d1d46e5
            - name: Import Secrets
              id: secrets
              uses: hashicorp/vault-action@7709c609789c5e27b757a85817483caadbb5939a
              with:
                  url: ${{ secrets.VAULT_ADDR }}
                  method: approle
                  roleId: ${{ secrets.VAULT_ROLE_ID }}
                  secretId: ${{ secrets.VAULT_SECRET_ID }}
                  exportEnv: false
                  secrets: |
                      secret/data/products/infrastructure-experience/ci/common AWS_ACCESS_KEY;
                      secret/data/products/infrastructure-experience/ci/common AWS_SECRET_KEY;
            - name: Add profile credentials to ~/.aws/credentials
              shell: bash
              run: |
                  aws configure set aws_access_key_id ${{ steps.secrets.outputs.AWS_ACCESS_KEY }} --profile ${{ env.AWS_PROFILE }}
                  aws configure set aws_secret_access_key ${{ steps.secrets.outputs.AWS_SECRET_KEY }} --profile ${{ env.AWS_PROFILE }}
                  aws configure set region ${{ env.AWS_REGION }} --profile ${{ env.AWS_PROFILE }}
            - name: Export test prefix
              run: |
                  prefix="ec2-test-$(tr -dc 'a-z0-9' </dev/urandom | head -c 5)"
                  echo "TF_PREFIX=${prefix}" >> "$GITHUB_ENV"
            - name: Replace matrix dots with hyphen
              run: |
                  version=$(echo "${{ matrix.camunda }}" | tr '.' '-')
                  echo "CAMUNDA_HYPHENS=$version" >> "$GITHUB_ENV"
            - name: Configure Terraform Backend
              run: |
                  cp ${{ github.workspace }}/aws/ec2/test/fixtures/*.tf ${{ github.workspace }}/aws/ec2/terraform/
                  echo "TF_CLI_ARGS_init=-backend-config='bucket=${{ env.S3_BACKEND_BUCKET }}' -backend-config='key=state/${{ env.TF_PREFIX }}/terraform.tfstate' -backend-config='region=${{ env.S3_BUCKET_REGION }}' -backend-config='encrypt=true'" >> "$GITHUB_ENV"
            - name: Set Camunda version
              working-directory: aws/ec2/scripts
              run: |
                  # We need to replace the string without substitution except for that of GitHub Actions
                  # shellcheck disable=SC2016
                  sed -i '0,/CAMUNDA_VERSION/s/CAMUNDA_VERSION=.*/CAMUNDA_VERSION=${CAMUNDA_VERSION:-"${{ matrix.camunda }}"}/' camunda-install.sh
            - name: Overwrite previous version
              run: |
                  if [[ "${{matrix.camunda }}" =~ "SNAPSHOT" ]]; then
                      echo "CAMUNDA_PREVIOUS_VERSION=${{ env.SNAPSHOT_PREVIOUS_VERSION }}" >> "$GITHUB_ENV"
                  else
                      echo "CAMUNDA_PREVIOUS_VERSION=${{ matrix.previous_camunda }}" >> "$GITHUB_ENV"
                  fi
            - name: Terratest - Terraform Apply
              if: always() && success()
              working-directory: aws/ec2/test/src
              timeout-minutes: 61
              run: |
                  go test -v -timeout 60m -run TestSetup
              env:
                  ARCHITECTURE: ${{ matrix.architecture }}
            - name: Terratest - Run all Tests
              id: terratest
              working-directory: aws/ec2/test/src
              timeout-minutes: 121
              env:
                  CAMUNDA_VERSION: ${{ matrix.camunda }}
                  CAMUNDA_PREVIOUS_VERSION: ${{ env.CAMUNDA_PREVIOUS_VERSION }}
              run: |
                  # shellcheck disable=SC2155
                  export PATH=$PATH:$(go env GOPATH)/bin
                  mkdir /home/runner/.ssh
                  touch /home/runner/.ssh/config

                  go install gotest.tools/gotestsum@latest
                  # Run all tests except TestSetup and TestTeardown
                  go run gotest.tools/gotestsum@latest --junitfile tests.xml -- --timeout=120m --skip 'TestSetup|TestTeardown'
            - name: Terratest - Terraform Destroy
              if: always()
              id: tf-destroy
              working-directory: aws/ec2/test/src
              timeout-minutes: 31
              run: |
                  go test -v -timeout 30m -run TestTeardown
            - name: Filter logger.go from the test report (too large)
              if: always()
              working-directory: aws/ec2/test/src
              run: |
                  sed 's/&#xA;/\n/g' < "./tests.xml" |
                  grep -E -v '^.*logger\.go.*$' |
                  sed 's/\n/&#xA;/g' > "./tests-${{ env.CAMUNDA_HYPHENS }}-filtered.xml"
            - name: Upload test reports
              if: always()
              uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
              with:
                  name: test-reports-${{ env.CAMUNDA_HYPHENS }}-${{ matrix.architecture }}
                  path: ${{ github.workspace }}/aws/ec2/test/src/tests-${{ env.CAMUNDA_HYPHENS }}-filtered.xml
                  retention-days: 7
            - name: Cleanup S3 state bucket
              if: always() && steps.tf-destroy.outcome == 'success'
              run: |
                  aws s3 rm "s3://tf-state-multi-reg/state/${TF_PREFIX}/terraform.tfstate"
            - name: Remove profile credentials from ~/.aws/credentials
              if: always()
              run: |
                  rm -rf ~/.aws/credentials
    test-report:
        runs-on: ubuntu-latest
        if: always()
        needs:
            - test
        outputs:
            SNAPSHOT_ERROR: ${{ steps.determine-if-failed-tests-include-snapshot.outputs.SNAPSHOT_ERROR }}
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806
              with:
                  pattern: test-reports-*
                  path: /tmp/testreports
                  merge-multiple: true
            - name: Determine if failed tests include SNAPSHOT
              id: determine-if-failed-tests-include-snapshot
              run: |
                  file=$(find /tmp/testreports -name "*SNAPSHOT*.xml" -type f)
                  echo "Found file: $file"
                  if grep -q "FAIL" "$file"; then
                    echo "File containing 'SNAPSHOT' with FAIL exists"
                    echo "SNAPSHOT_ERROR=true" >> "$GITHUB_OUTPUT"
                  else
                    echo "No file containing 'SNAPSHOT' or with FAIL found"
                    echo "SNAPSHOT_ERROR=false" >> "$GITHUB_OUTPUT"
                  fi
            - name: Run test-summary
              uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86
              with:
                  paths: /tmp/testreports/**/*.xml
    notify-on-failure:
        runs-on: ubuntu-latest
        if: failure() && needs.test-report.outputs.SNAPSHOT_ERROR == 'false'
        needs:
            - test
            - test-report
        steps:
            - name: Notify in Slack in case of failure
              id: slack-notification
              if: ${{ env.IS_SCHEDULE == 'true' }}
              uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@e9a9f33ab193348a82a79bd9250fdf12f708390a
              with:
                  vault_addr: ${{ secrets.VAULT_ADDR }}
                  vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
                  vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
