---
name: Internal - Global - Pull Request Labeler
on:
    pull_request_target:
    schedule:
        - cron: 0 1 * * 1
    pull_request:
        paths:
            - .github/workflows/labeler.yml

jobs:
    labeler:
        permissions:
            contents: read
            pull-requests: write # only allow updates of the tags
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7

            - name: Notify in Slack in case of failure
              id: slack-notification
              if: failure()
              uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@bde1b69728d323c1c2d02e19153a8e00382eec4a # 1.8.0
              with:
                  vault_addr: ${{ secrets.VAULT_ADDR }}
                  vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
                  vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
                  slack_channel_id: ${{ github.event_name == 'schedule' && 'C076N4G1162' || 'C07E4FF6YMB' }}
                  slack_mention_people: ${{ github.event_name == 'schedule' && '@infraex-medic' || '' }}
                  disable_silence_check: ${{ github.event_name == 'schedule' && 'false' || 'true' }}
