---
name: Internal - Global - Branches Schedule Workflows

on:
    pull_request:
        paths:
            - .github/workflows/internal_branches_workflow_scheduler.yml
    schedule:
        - cron: 0 * * * *   # every hour, every day

jobs:
    define-matrix:
        runs-on: ubuntu-latest
        outputs:
            schedules: ${{ steps.matrix.outputs.schedules }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                  fetch-depth: 0

            - name: Install asdf tools with cache
              uses: camunda/infraex-common-config/./.github/actions/asdf-install-tooling@6dc218bf7ee3812a4b6b13c305bce60d5d1d46e5 # 1.3.1

            - id: matrix
              run: |
                  set -euxo pipefail # tolerate, nothing.

                  # shellcheck disable=SC2086
                  schedules="$(yq '.schedules' --indent=0 --output-format json .github/workflows-config/workflow-scheduler.yml)"

                  # Convert each workflow_files array to a string format
                  formatted_schedules=$(echo "$schedules" | jq '.[].workflow_files |= tostring')

                  echo "schedules=${formatted_schedules}" | tee -a "$GITHUB_OUTPUT"

    schedule-workflows:
        runs-on: ubuntu-latest
        needs:
            - define-matrix
        strategy:
            fail-fast: false
            matrix:
                schedule: ${{ fromJson(needs.define-matrix.outputs.schedules) }}
        steps:
            - name: Install asdf tools with cache
              uses: camunda/infraex-common-config/./.github/actions/asdf-install-tooling@6dc218bf7ee3812a4b6b13c305bce60d5d1d46e5 # 1.3.1

            - name: Generate token for GitHub
              id: generate-github-token
              uses: camunda/infra-global-github-actions/generate-github-app-token-from-vault-secrets@a6a9d41844431ce3a5edc43a0f446ed19fca9e25 # main
              with:
                  github-app-id-vault-key: GITHUB_APP_ID
                  github-app-id-vault-path: secret/data/products/infrastructure-experience/ci/common
                  github-app-private-key-vault-key: GITHUB_APP_PRIVATE_KEY
                  github-app-private-key-vault-path: secret/data/products/infrastructure-experience/ci/common
                  vault-auth-method: approle
                  vault-auth-role-id: ${{ secrets.VAULT_ROLE_ID }}
                  vault-auth-secret-id: ${{ secrets.VAULT_SECRET_ID }}
                  vault-url: ${{ secrets.VAULT_ADDR }}

            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                  token: ${{ steps.generate-github-token.outputs.token }}
                  ref: ${{ matrix.schedule.branch }}

            - name: Prepare the working branch
              run: |
                  stringified_branch=$(echo "${{ matrix.schedule.name }}" | tr ' ' '_' | tr -cd '[:alnum:]_')

                  if git show-ref --verify --quiet "refs/heads/schedules/$stringified_branch"; then
                    git push origin --delete "schedules/$stringified_branch"
                  fi

                  git checkout -b "schedules/$stringified_branch"

            - name: Modify workflow files to trigger the PR
              run: |
                  workflow_files=$(echo "${{ matrix.schedule.workflow_files }}" | jq -r '.[]')
                  echo "Removing on.pull_request.paths from $workflow_files"

                  # Loop through each workflow file and modify it using yq
                  echo "$workflow_files" | while IFS= read -r workflow_file; do
                    yq -i 'del(.on.pull_request.path)' "$workflow_file"
                  done

            - name: Commit Changes
              uses: getsentry/action-github-commit@5972d5f578ad77306063449e718c0c2a6fbc4ae1 # main
              with:
                  github-token: ${{ steps.generate-github-token.outputs.token }}
                  message: 'chore: update schedule files'
