---
name: Internal - Global - Lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/lint-global.yml@83b06cabc31dc3a09ef33e9131f5e6de575d1c9c # 2.1.0
        secrets: inherit
