---
# This workflow updates an artifact containing the ROSA versions,
# it's used by renovate and published at https://camunda.github.io/camunda-deployment-references/rosa_versions.txt
name: Internal - OpenShift - Save ROSA Versions as an artifact

on:
    schedule:
        - cron: 0 0 * * *
    workflow_dispatch:
    pull_request:
        paths:
            - .github/workflows/internal_openshift_artifact_rosa_versions.yml

jobs:
    save-rosa-versions:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                  ref: gh-pages

            - name: Import Secrets
              id: secrets
              uses: hashicorp/vault-action@7709c609789c5e27b757a85817483caadbb5939a # v3
              with:
                  url: ${{ secrets.VAULT_ADDR }}
                  method: approle
                  roleId: ${{ secrets.VAULT_ROLE_ID }}
                  secretId: ${{ secrets.VAULT_SECRET_ID }}
                  exportEnv: false
                  secrets: |
                      secret/data/products/infrastructure-experience/ci/common RH_OPENSHIFT_TOKEN;

            - name: Install ROSA CLI and output rosa versions
              shell: bash
              working-directory: /tmp
              run: |
                  set -euo pipefail

                  curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/rosa-linux.tar.gz"
                  tar -xvf rosa-linux.tar.gz
                  sudo mv rosa /usr/local/bin/rosa
                  chmod +x /usr/local/bin/rosa
                  rm -f rosa-linux.tar.gz
                  rosa version
                  rosa login --token=${{ steps.secrets.outputs.RH_OPENSHIFT_TOKEN }}
                  mkdir -p docs
                  rosa list versions --output json | jq '.[].raw_id' --raw-output > docs/rosa_versions.txt

            - name: Commit and push ROSA versions file to gh-pages
              shell: bash
              run: |
                  set -euo pipefail

                  git diff --exit-code docs/rosa_versions.txt || {
                    git config --local user.name "github-actions[bot]"
                    git config --local user.email "github-actions[bot]@users.noreply.github.com"
                    git add docs/rosa_versions.txt
                    git commit -m "Update ROSA versions"
                    git push origin gh-pages
                  }
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Notify in Slack in case of failure
              id: slack-notification
              if: failure() && github.event_name == 'schedule'
              uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@14912e07221cd650bf9286e2a4733a138ca46374 # 1.3.6
              with:
                  vault_addr: ${{ secrets.VAULT_ADDR }}
                  vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
                  vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
