---
name: Internal - Global - Lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/lint-global.yml@6d3ddc1bbae80d4c7bb42541ba7f0e95a2ef9787 # 1.6.1
        secrets: inherit
