---
name: Internal - Global - Check external links

on:
    workflow_dispatch:
    schedule:
        - cron: 0 3 * * *
    pull_request:
        paths:
            - .github/workflows/internal_global_links.yml
            - '**/*.md'

env:
    IS_SCHEDULE: ${{ (contains(github.head_ref, 'schedules/') || github.event_name == 'schedule') && 'true' || 'false' }}

jobs:
    lint:
        name: links-check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

            - name: Link Checker
              uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
              with:
                  fail: true
                  args: -c ./lychee-links.toml . --verbose --no-progress '*.md' './**/*.md'
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Issue From File
              if: failure() && env.IS_SCHEDULE == 'true'
              uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6
              with:
                  issue-number: 3472
                  title: Link Checker Report
                  content-filepath: ./lychee/out.md
                  labels: report, automated issue
                  assignees: '@camunda/infraex-medic'

            - name: Reopen Link Checker Report
              if: failure() && env.IS_SCHEDULE == 'true' && hashFiles('lychee/out.md') != ''
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh api --method PATCH "repos/${GITHUB_REPOSITORY}/issues/3472" -f state=open >/dev/null

            - name: Notify in Slack in case of failure
              id: slack-notification
              uses: camunda/infraex-common-config/.github/actions/report-failure-on-slack@fc5fa6ee1e142bf583e9f01e749bc31654ff07ac # 2.3.8
              if: failure()
              with:
                  vault_addr: ${{ secrets.VAULT_ADDR }}
                  vault_role_id: ${{ secrets.VAULT_ROLE_ID }}
                  vault_secret_id: ${{ secrets.VAULT_SECRET_ID }}
                  slack_channel_id: ${{ env.IS_SCHEDULE == 'true' && 'C076N4G1162' || 'C07E4FF6YMB' }}
                  slack_mention_people: ${{ env.IS_SCHEDULE == 'true' && '@infraex-medic' || '' }}
                  disable_silence_check: ${{ env.IS_SCHEDULE == 'true' && 'false' || 'true' }}
