---
name: lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/lint-global.yml@bf2a95a9ad449bb221a5958537a94ec129270002 # 1.2.10
        secrets: inherit
