---
name: lint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: camunda/infraex-common-config/.github/workflows/lint-global.yml@4fb817ed556456048fd646e637f8d0e6ba6d9ed9
        secrets: inherit
