---
name: Renovate Auto Merge

on:
    pull_request:

# limit to a single execution per ref of this workflow
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    renovate-automerge:
        uses: camunda/infraex-common-config/.github/workflows/automerge-global.yml@bf2a95a9ad449bb221a5958537a94ec129270002 # 1.2.10
        secrets: inherit
