---
name: Test Bash Functions with Custom Shell

on:
    push:
    workflow_dispatch:

jobs:
    test-bash-funcs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Add custom shell to PATH
              run: echo "${GITHUB_WORKSPACE}/scripts" >> "$GITHUB_PATH"

            - name: Test Bash functions
              shell: custom-bash.sh
              run: |
                  say_hello
                  show_time
