---
name: Test Bash Functions with Custom Shell

on:
    push:
    workflow_dispatch:

jobs:
    test-bash-funcs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - run: |
                  touch ./bash
                  chmod +x ./bash
                  echo '#!/bin/sh' > ./bash
                  echo ". ${GITHUB_WORKSPACE}/gha-functions.sh" >> ./bash
                  echo 'bash "$@"' >> ./bash
                  echo "${PWD}" >> "${GITHUB_PATH}"
            - run: |
                  echo "this doesn't do what you expect"
                  show_time
              shell: bash
