---
name: Test Bash Functions with Custom Shell

on:
    push:
    workflow_dispatch:

jobs:
    test-bash-funcs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Add custom shell to PATH
              run: echo "${GITHUB_WORKSPACE}/scripts" >> "$GITHUB_PATH" 

            - run: |
                touch ./bash
                chmod +x ./bash
                echo '#!/bin/sh' > ./bash
                echo 'echo hello from fake bash' >> ./bash
                echo "${PWD}" >> "${GITHUB_PATH}"
            - run: |
                echo "this doesn't do what you expect"
              shell: bash
